[build]
  base = "frontend"
  command = "mkdir -p public && echo \"/api/* $VITE_API_URL/:splat 200!\" > public/_redirects && echo \"/* /index.html 200\" >> public/_redirects && npm install && npm run build"
  publish = "dist"
