/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/VehicleInfo.ts';
export type * from './models/LocationLog.ts';
export type * from './models/User.ts';
export type * from './models/Geofence.ts';
export type * from './models/VehicleCompliance.ts';
export type * from './commonInputTypes.ts';
