/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `LocationLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model LocationLog
 *
 */
export type LocationLogModel = runtime.Types.Result.DefaultSelection<Prisma.$LocationLogPayload>;

export type AggregateLocationLog = {
  _count: LocationLogCountAggregateOutputType | null;
  _avg: LocationLogAvgAggregateOutputType | null;
  _sum: LocationLogSumAggregateOutputType | null;
  _min: LocationLogMinAggregateOutputType | null;
  _max: LocationLogMaxAggregateOutputType | null;
};

export type LocationLogAvgAggregateOutputType = {
  lat: runtime.Decimal | null;
  lng: runtime.Decimal | null;
  altitude: runtime.Decimal | null;
  speed: runtime.Decimal | null;
  heading: runtime.Decimal | null;
  batteryVoltage: number | null;
};

export type LocationLogSumAggregateOutputType = {
  lat: runtime.Decimal | null;
  lng: runtime.Decimal | null;
  altitude: runtime.Decimal | null;
  speed: runtime.Decimal | null;
  heading: runtime.Decimal | null;
  batteryVoltage: number | null;
};

export type LocationLogMinAggregateOutputType = {
  id: string | null;
  imei: string | null;
  lat: runtime.Decimal | null;
  lng: runtime.Decimal | null;
  altitude: runtime.Decimal | null;
  speed: runtime.Decimal | null;
  heading: runtime.Decimal | null;
  batteryVoltage: number | null;
  ignition: boolean | null;
  timestamp: Date | null;
  createdAt: Date | null;
};

export type LocationLogMaxAggregateOutputType = {
  id: string | null;
  imei: string | null;
  lat: runtime.Decimal | null;
  lng: runtime.Decimal | null;
  altitude: runtime.Decimal | null;
  speed: runtime.Decimal | null;
  heading: runtime.Decimal | null;
  batteryVoltage: number | null;
  ignition: boolean | null;
  timestamp: Date | null;
  createdAt: Date | null;
};

export type LocationLogCountAggregateOutputType = {
  id: number;
  imei: number;
  lat: number;
  lng: number;
  altitude: number;
  speed: number;
  heading: number;
  batteryVoltage: number;
  ignition: number;
  timestamp: number;
  createdAt: number;
  _all: number;
};

export type LocationLogAvgAggregateInputType = {
  lat?: true;
  lng?: true;
  altitude?: true;
  speed?: true;
  heading?: true;
  batteryVoltage?: true;
};

export type LocationLogSumAggregateInputType = {
  lat?: true;
  lng?: true;
  altitude?: true;
  speed?: true;
  heading?: true;
  batteryVoltage?: true;
};

export type LocationLogMinAggregateInputType = {
  id?: true;
  imei?: true;
  lat?: true;
  lng?: true;
  altitude?: true;
  speed?: true;
  heading?: true;
  batteryVoltage?: true;
  ignition?: true;
  timestamp?: true;
  createdAt?: true;
};

export type LocationLogMaxAggregateInputType = {
  id?: true;
  imei?: true;
  lat?: true;
  lng?: true;
  altitude?: true;
  speed?: true;
  heading?: true;
  batteryVoltage?: true;
  ignition?: true;
  timestamp?: true;
  createdAt?: true;
};

export type LocationLogCountAggregateInputType = {
  id?: true;
  imei?: true;
  lat?: true;
  lng?: true;
  altitude?: true;
  speed?: true;
  heading?: true;
  batteryVoltage?: true;
  ignition?: true;
  timestamp?: true;
  createdAt?: true;
  _all?: true;
};

export type LocationLogAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which LocationLog to aggregate.
   */
  where?: Prisma.LocationLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of LocationLogs to fetch.
   */
  orderBy?:
    | Prisma.LocationLogOrderByWithRelationInput
    | Prisma.LocationLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.LocationLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` LocationLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` LocationLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned LocationLogs
   **/
  _count?: true | LocationLogCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: LocationLogAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: LocationLogSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: LocationLogMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: LocationLogMaxAggregateInputType;
};

export type GetLocationLogAggregateType<T extends LocationLogAggregateArgs> = {
  [P in keyof T & keyof AggregateLocationLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLocationLog[P]>
    : Prisma.GetScalarType<T[P], AggregateLocationLog[P]>;
};

export type LocationLogGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.LocationLogWhereInput;
  orderBy?:
    | Prisma.LocationLogOrderByWithAggregationInput
    | Prisma.LocationLogOrderByWithAggregationInput[];
  by: Prisma.LocationLogScalarFieldEnum[] | Prisma.LocationLogScalarFieldEnum;
  having?: Prisma.LocationLogScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: LocationLogCountAggregateInputType | true;
  _avg?: LocationLogAvgAggregateInputType;
  _sum?: LocationLogSumAggregateInputType;
  _min?: LocationLogMinAggregateInputType;
  _max?: LocationLogMaxAggregateInputType;
};

export type LocationLogGroupByOutputType = {
  id: string;
  imei: string;
  lat: runtime.Decimal;
  lng: runtime.Decimal;
  altitude: runtime.Decimal | null;
  speed: runtime.Decimal | null;
  heading: runtime.Decimal | null;
  batteryVoltage: number | null;
  ignition: boolean;
  timestamp: Date;
  createdAt: Date;
  _count: LocationLogCountAggregateOutputType | null;
  _avg: LocationLogAvgAggregateOutputType | null;
  _sum: LocationLogSumAggregateOutputType | null;
  _min: LocationLogMinAggregateOutputType | null;
  _max: LocationLogMaxAggregateOutputType | null;
};

type GetLocationLogGroupByPayload<T extends LocationLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LocationLogGroupByOutputType, T['by']> & {
      [P in keyof T & keyof LocationLogGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], LocationLogGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], LocationLogGroupByOutputType[P]>;
    }
  >
>;

export type LocationLogWhereInput = {
  AND?: Prisma.LocationLogWhereInput | Prisma.LocationLogWhereInput[];
  OR?: Prisma.LocationLogWhereInput[];
  NOT?: Prisma.LocationLogWhereInput | Prisma.LocationLogWhereInput[];
  id?: Prisma.UuidFilter<'LocationLog'> | string;
  imei?: Prisma.StringFilter<'LocationLog'> | string;
  lat?:
    | Prisma.DecimalFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.DecimalNullableFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.DecimalNullableFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.DecimalNullableFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.FloatNullableFilter<'LocationLog'> | number | null;
  ignition?: Prisma.BoolFilter<'LocationLog'> | boolean;
  timestamp?: Prisma.DateTimeFilter<'LocationLog'> | Date | string;
  createdAt?: Prisma.DateTimeFilter<'LocationLog'> | Date | string;
  vehicle?: Prisma.XOR<Prisma.VehicleInfoScalarRelationFilter, Prisma.VehicleInfoWhereInput>;
};

export type LocationLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  imei?: Prisma.SortOrder;
  lat?: Prisma.SortOrder;
  lng?: Prisma.SortOrder;
  altitude?: Prisma.SortOrderInput | Prisma.SortOrder;
  speed?: Prisma.SortOrderInput | Prisma.SortOrder;
  heading?: Prisma.SortOrderInput | Prisma.SortOrder;
  batteryVoltage?: Prisma.SortOrderInput | Prisma.SortOrder;
  ignition?: Prisma.SortOrder;
  timestamp?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  vehicle?: Prisma.VehicleInfoOrderByWithRelationInput;
};

export type LocationLogWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.LocationLogWhereInput | Prisma.LocationLogWhereInput[];
    OR?: Prisma.LocationLogWhereInput[];
    NOT?: Prisma.LocationLogWhereInput | Prisma.LocationLogWhereInput[];
    imei?: Prisma.StringFilter<'LocationLog'> | string;
    lat?:
      | Prisma.DecimalFilter<'LocationLog'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string;
    lng?:
      | Prisma.DecimalFilter<'LocationLog'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string;
    altitude?:
      | Prisma.DecimalNullableFilter<'LocationLog'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string
      | null;
    speed?:
      | Prisma.DecimalNullableFilter<'LocationLog'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string
      | null;
    heading?:
      | Prisma.DecimalNullableFilter<'LocationLog'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string
      | null;
    batteryVoltage?: Prisma.FloatNullableFilter<'LocationLog'> | number | null;
    ignition?: Prisma.BoolFilter<'LocationLog'> | boolean;
    timestamp?: Prisma.DateTimeFilter<'LocationLog'> | Date | string;
    createdAt?: Prisma.DateTimeFilter<'LocationLog'> | Date | string;
    vehicle?: Prisma.XOR<Prisma.VehicleInfoScalarRelationFilter, Prisma.VehicleInfoWhereInput>;
  },
  'id'
>;

export type LocationLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  imei?: Prisma.SortOrder;
  lat?: Prisma.SortOrder;
  lng?: Prisma.SortOrder;
  altitude?: Prisma.SortOrderInput | Prisma.SortOrder;
  speed?: Prisma.SortOrderInput | Prisma.SortOrder;
  heading?: Prisma.SortOrderInput | Prisma.SortOrder;
  batteryVoltage?: Prisma.SortOrderInput | Prisma.SortOrder;
  ignition?: Prisma.SortOrder;
  timestamp?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  _count?: Prisma.LocationLogCountOrderByAggregateInput;
  _avg?: Prisma.LocationLogAvgOrderByAggregateInput;
  _max?: Prisma.LocationLogMaxOrderByAggregateInput;
  _min?: Prisma.LocationLogMinOrderByAggregateInput;
  _sum?: Prisma.LocationLogSumOrderByAggregateInput;
};

export type LocationLogScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.LocationLogScalarWhereWithAggregatesInput
    | Prisma.LocationLogScalarWhereWithAggregatesInput[];
  OR?: Prisma.LocationLogScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.LocationLogScalarWhereWithAggregatesInput
    | Prisma.LocationLogScalarWhereWithAggregatesInput[];
  id?: Prisma.UuidWithAggregatesFilter<'LocationLog'> | string;
  imei?: Prisma.StringWithAggregatesFilter<'LocationLog'> | string;
  lat?:
    | Prisma.DecimalWithAggregatesFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalWithAggregatesFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.DecimalNullableWithAggregatesFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.DecimalNullableWithAggregatesFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.DecimalNullableWithAggregatesFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.FloatNullableWithAggregatesFilter<'LocationLog'> | number | null;
  ignition?: Prisma.BoolWithAggregatesFilter<'LocationLog'> | boolean;
  timestamp?: Prisma.DateTimeWithAggregatesFilter<'LocationLog'> | Date | string;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'LocationLog'> | Date | string;
};

export type LocationLogCreateInput = {
  id?: string;
  lat: runtime.Decimal | runtime.DecimalJsLike | number | string;
  lng: runtime.Decimal | runtime.DecimalJsLike | number | string;
  altitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  speed?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  heading?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  batteryVoltage?: number | null;
  ignition?: boolean;
  timestamp: Date | string;
  createdAt?: Date | string;
  vehicle: Prisma.VehicleInfoCreateNestedOneWithoutLocationsInput;
};

export type LocationLogUncheckedCreateInput = {
  id?: string;
  imei: string;
  lat: runtime.Decimal | runtime.DecimalJsLike | number | string;
  lng: runtime.Decimal | runtime.DecimalJsLike | number | string;
  altitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  speed?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  heading?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  batteryVoltage?: number | null;
  ignition?: boolean;
  timestamp: Date | string;
  createdAt?: Date | string;
};

export type LocationLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  lat?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  ignition?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  vehicle?: Prisma.VehicleInfoUpdateOneRequiredWithoutLocationsNestedInput;
};

export type LocationLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  imei?: Prisma.StringFieldUpdateOperationsInput | string;
  lat?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  ignition?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LocationLogCreateManyInput = {
  id?: string;
  imei: string;
  lat: runtime.Decimal | runtime.DecimalJsLike | number | string;
  lng: runtime.Decimal | runtime.DecimalJsLike | number | string;
  altitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  speed?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  heading?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  batteryVoltage?: number | null;
  ignition?: boolean;
  timestamp: Date | string;
  createdAt?: Date | string;
};

export type LocationLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  lat?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  ignition?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LocationLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  imei?: Prisma.StringFieldUpdateOperationsInput | string;
  lat?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  ignition?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LocationLogListRelationFilter = {
  every?: Prisma.LocationLogWhereInput;
  some?: Prisma.LocationLogWhereInput;
  none?: Prisma.LocationLogWhereInput;
};

export type LocationLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type LocationLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  imei?: Prisma.SortOrder;
  lat?: Prisma.SortOrder;
  lng?: Prisma.SortOrder;
  altitude?: Prisma.SortOrder;
  speed?: Prisma.SortOrder;
  heading?: Prisma.SortOrder;
  batteryVoltage?: Prisma.SortOrder;
  ignition?: Prisma.SortOrder;
  timestamp?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type LocationLogAvgOrderByAggregateInput = {
  lat?: Prisma.SortOrder;
  lng?: Prisma.SortOrder;
  altitude?: Prisma.SortOrder;
  speed?: Prisma.SortOrder;
  heading?: Prisma.SortOrder;
  batteryVoltage?: Prisma.SortOrder;
};

export type LocationLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  imei?: Prisma.SortOrder;
  lat?: Prisma.SortOrder;
  lng?: Prisma.SortOrder;
  altitude?: Prisma.SortOrder;
  speed?: Prisma.SortOrder;
  heading?: Prisma.SortOrder;
  batteryVoltage?: Prisma.SortOrder;
  ignition?: Prisma.SortOrder;
  timestamp?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type LocationLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  imei?: Prisma.SortOrder;
  lat?: Prisma.SortOrder;
  lng?: Prisma.SortOrder;
  altitude?: Prisma.SortOrder;
  speed?: Prisma.SortOrder;
  heading?: Prisma.SortOrder;
  batteryVoltage?: Prisma.SortOrder;
  ignition?: Prisma.SortOrder;
  timestamp?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type LocationLogSumOrderByAggregateInput = {
  lat?: Prisma.SortOrder;
  lng?: Prisma.SortOrder;
  altitude?: Prisma.SortOrder;
  speed?: Prisma.SortOrder;
  heading?: Prisma.SortOrder;
  batteryVoltage?: Prisma.SortOrder;
};

export type LocationLogCreateNestedManyWithoutVehicleInput = {
  create?:
    | Prisma.XOR<
        Prisma.LocationLogCreateWithoutVehicleInput,
        Prisma.LocationLogUncheckedCreateWithoutVehicleInput
      >
    | Prisma.LocationLogCreateWithoutVehicleInput[]
    | Prisma.LocationLogUncheckedCreateWithoutVehicleInput[];
  connectOrCreate?:
    | Prisma.LocationLogCreateOrConnectWithoutVehicleInput
    | Prisma.LocationLogCreateOrConnectWithoutVehicleInput[];
  createMany?: Prisma.LocationLogCreateManyVehicleInputEnvelope;
  connect?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
};

export type LocationLogUncheckedCreateNestedManyWithoutVehicleInput = {
  create?:
    | Prisma.XOR<
        Prisma.LocationLogCreateWithoutVehicleInput,
        Prisma.LocationLogUncheckedCreateWithoutVehicleInput
      >
    | Prisma.LocationLogCreateWithoutVehicleInput[]
    | Prisma.LocationLogUncheckedCreateWithoutVehicleInput[];
  connectOrCreate?:
    | Prisma.LocationLogCreateOrConnectWithoutVehicleInput
    | Prisma.LocationLogCreateOrConnectWithoutVehicleInput[];
  createMany?: Prisma.LocationLogCreateManyVehicleInputEnvelope;
  connect?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
};

export type LocationLogUpdateManyWithoutVehicleNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.LocationLogCreateWithoutVehicleInput,
        Prisma.LocationLogUncheckedCreateWithoutVehicleInput
      >
    | Prisma.LocationLogCreateWithoutVehicleInput[]
    | Prisma.LocationLogUncheckedCreateWithoutVehicleInput[];
  connectOrCreate?:
    | Prisma.LocationLogCreateOrConnectWithoutVehicleInput
    | Prisma.LocationLogCreateOrConnectWithoutVehicleInput[];
  upsert?:
    | Prisma.LocationLogUpsertWithWhereUniqueWithoutVehicleInput
    | Prisma.LocationLogUpsertWithWhereUniqueWithoutVehicleInput[];
  createMany?: Prisma.LocationLogCreateManyVehicleInputEnvelope;
  set?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
  disconnect?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
  delete?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
  connect?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
  update?:
    | Prisma.LocationLogUpdateWithWhereUniqueWithoutVehicleInput
    | Prisma.LocationLogUpdateWithWhereUniqueWithoutVehicleInput[];
  updateMany?:
    | Prisma.LocationLogUpdateManyWithWhereWithoutVehicleInput
    | Prisma.LocationLogUpdateManyWithWhereWithoutVehicleInput[];
  deleteMany?: Prisma.LocationLogScalarWhereInput | Prisma.LocationLogScalarWhereInput[];
};

export type LocationLogUncheckedUpdateManyWithoutVehicleNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.LocationLogCreateWithoutVehicleInput,
        Prisma.LocationLogUncheckedCreateWithoutVehicleInput
      >
    | Prisma.LocationLogCreateWithoutVehicleInput[]
    | Prisma.LocationLogUncheckedCreateWithoutVehicleInput[];
  connectOrCreate?:
    | Prisma.LocationLogCreateOrConnectWithoutVehicleInput
    | Prisma.LocationLogCreateOrConnectWithoutVehicleInput[];
  upsert?:
    | Prisma.LocationLogUpsertWithWhereUniqueWithoutVehicleInput
    | Prisma.LocationLogUpsertWithWhereUniqueWithoutVehicleInput[];
  createMany?: Prisma.LocationLogCreateManyVehicleInputEnvelope;
  set?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
  disconnect?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
  delete?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
  connect?: Prisma.LocationLogWhereUniqueInput | Prisma.LocationLogWhereUniqueInput[];
  update?:
    | Prisma.LocationLogUpdateWithWhereUniqueWithoutVehicleInput
    | Prisma.LocationLogUpdateWithWhereUniqueWithoutVehicleInput[];
  updateMany?:
    | Prisma.LocationLogUpdateManyWithWhereWithoutVehicleInput
    | Prisma.LocationLogUpdateManyWithWhereWithoutVehicleInput[];
  deleteMany?: Prisma.LocationLogScalarWhereInput | Prisma.LocationLogScalarWhereInput[];
};

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string;
};

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string;
};

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null;
  increment?: number;
  decrement?: number;
  multiply?: number;
  divide?: number;
};

export type BoolFieldUpdateOperationsInput = {
  set?: boolean;
};

export type LocationLogCreateWithoutVehicleInput = {
  id?: string;
  lat: runtime.Decimal | runtime.DecimalJsLike | number | string;
  lng: runtime.Decimal | runtime.DecimalJsLike | number | string;
  altitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  speed?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  heading?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  batteryVoltage?: number | null;
  ignition?: boolean;
  timestamp: Date | string;
  createdAt?: Date | string;
};

export type LocationLogUncheckedCreateWithoutVehicleInput = {
  id?: string;
  lat: runtime.Decimal | runtime.DecimalJsLike | number | string;
  lng: runtime.Decimal | runtime.DecimalJsLike | number | string;
  altitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  speed?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  heading?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  batteryVoltage?: number | null;
  ignition?: boolean;
  timestamp: Date | string;
  createdAt?: Date | string;
};

export type LocationLogCreateOrConnectWithoutVehicleInput = {
  where: Prisma.LocationLogWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.LocationLogCreateWithoutVehicleInput,
    Prisma.LocationLogUncheckedCreateWithoutVehicleInput
  >;
};

export type LocationLogCreateManyVehicleInputEnvelope = {
  data: Prisma.LocationLogCreateManyVehicleInput | Prisma.LocationLogCreateManyVehicleInput[];
  skipDuplicates?: boolean;
};

export type LocationLogUpsertWithWhereUniqueWithoutVehicleInput = {
  where: Prisma.LocationLogWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.LocationLogUpdateWithoutVehicleInput,
    Prisma.LocationLogUncheckedUpdateWithoutVehicleInput
  >;
  create: Prisma.XOR<
    Prisma.LocationLogCreateWithoutVehicleInput,
    Prisma.LocationLogUncheckedCreateWithoutVehicleInput
  >;
};

export type LocationLogUpdateWithWhereUniqueWithoutVehicleInput = {
  where: Prisma.LocationLogWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.LocationLogUpdateWithoutVehicleInput,
    Prisma.LocationLogUncheckedUpdateWithoutVehicleInput
  >;
};

export type LocationLogUpdateManyWithWhereWithoutVehicleInput = {
  where: Prisma.LocationLogScalarWhereInput;
  data: Prisma.XOR<
    Prisma.LocationLogUpdateManyMutationInput,
    Prisma.LocationLogUncheckedUpdateManyWithoutVehicleInput
  >;
};

export type LocationLogScalarWhereInput = {
  AND?: Prisma.LocationLogScalarWhereInput | Prisma.LocationLogScalarWhereInput[];
  OR?: Prisma.LocationLogScalarWhereInput[];
  NOT?: Prisma.LocationLogScalarWhereInput | Prisma.LocationLogScalarWhereInput[];
  id?: Prisma.UuidFilter<'LocationLog'> | string;
  imei?: Prisma.StringFilter<'LocationLog'> | string;
  lat?:
    | Prisma.DecimalFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.DecimalNullableFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.DecimalNullableFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.DecimalNullableFilter<'LocationLog'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.FloatNullableFilter<'LocationLog'> | number | null;
  ignition?: Prisma.BoolFilter<'LocationLog'> | boolean;
  timestamp?: Prisma.DateTimeFilter<'LocationLog'> | Date | string;
  createdAt?: Prisma.DateTimeFilter<'LocationLog'> | Date | string;
};

export type LocationLogCreateManyVehicleInput = {
  id?: string;
  lat: runtime.Decimal | runtime.DecimalJsLike | number | string;
  lng: runtime.Decimal | runtime.DecimalJsLike | number | string;
  altitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  speed?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  heading?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  batteryVoltage?: number | null;
  ignition?: boolean;
  timestamp: Date | string;
  createdAt?: Date | string;
};

export type LocationLogUpdateWithoutVehicleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  lat?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  ignition?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LocationLogUncheckedUpdateWithoutVehicleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  lat?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  ignition?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LocationLogUncheckedUpdateManyWithoutVehicleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  lat?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  lng?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  altitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  speed?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  heading?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  batteryVoltage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  ignition?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LocationLogSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    imei?: boolean;
    lat?: boolean;
    lng?: boolean;
    altitude?: boolean;
    speed?: boolean;
    heading?: boolean;
    batteryVoltage?: boolean;
    ignition?: boolean;
    timestamp?: boolean;
    createdAt?: boolean;
    vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['locationLog']
>;

export type LocationLogSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    imei?: boolean;
    lat?: boolean;
    lng?: boolean;
    altitude?: boolean;
    speed?: boolean;
    heading?: boolean;
    batteryVoltage?: boolean;
    ignition?: boolean;
    timestamp?: boolean;
    createdAt?: boolean;
    vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['locationLog']
>;

export type LocationLogSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    imei?: boolean;
    lat?: boolean;
    lng?: boolean;
    altitude?: boolean;
    speed?: boolean;
    heading?: boolean;
    batteryVoltage?: boolean;
    ignition?: boolean;
    timestamp?: boolean;
    createdAt?: boolean;
    vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['locationLog']
>;

export type LocationLogSelectScalar = {
  id?: boolean;
  imei?: boolean;
  lat?: boolean;
  lng?: boolean;
  altitude?: boolean;
  speed?: boolean;
  heading?: boolean;
  batteryVoltage?: boolean;
  ignition?: boolean;
  timestamp?: boolean;
  createdAt?: boolean;
};

export type LocationLogOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'imei'
  | 'lat'
  | 'lng'
  | 'altitude'
  | 'speed'
  | 'heading'
  | 'batteryVoltage'
  | 'ignition'
  | 'timestamp'
  | 'createdAt',
  ExtArgs['result']['locationLog']
>;
export type LocationLogInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
};
export type LocationLogIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
};
export type LocationLogIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
};

export type $LocationLogPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'LocationLog';
  objects: {
    vehicle: Prisma.$VehicleInfoPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      imei: string;
      lat: runtime.Decimal;
      lng: runtime.Decimal;
      altitude: runtime.Decimal | null;
      speed: runtime.Decimal | null;
      heading: runtime.Decimal | null;
      batteryVoltage: number | null;
      ignition: boolean;
      timestamp: Date;
      createdAt: Date;
    },
    ExtArgs['result']['locationLog']
  >;
  composites: {};
};

export type LocationLogGetPayload<S extends boolean | null | undefined | LocationLogDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$LocationLogPayload, S>;

export type LocationLogCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<LocationLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: LocationLogCountAggregateInputType | true;
};

export interface LocationLogDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['LocationLog'];
    meta: { name: 'LocationLog' };
  };
  /**
   * Find zero or one LocationLog that matches the filter.
   * @param {LocationLogFindUniqueArgs} args - Arguments to find a LocationLog
   * @example
   * // Get one LocationLog
   * const locationLog = await prisma.locationLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LocationLogFindUniqueArgs>(
    args: Prisma.SelectSubset<T, LocationLogFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__LocationLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one LocationLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LocationLogFindUniqueOrThrowArgs} args - Arguments to find a LocationLog
   * @example
   * // Get one LocationLog
   * const locationLog = await prisma.locationLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LocationLogFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, LocationLogFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__LocationLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first LocationLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocationLogFindFirstArgs} args - Arguments to find a LocationLog
   * @example
   * // Get one LocationLog
   * const locationLog = await prisma.locationLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LocationLogFindFirstArgs>(
    args?: Prisma.SelectSubset<T, LocationLogFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__LocationLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first LocationLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocationLogFindFirstOrThrowArgs} args - Arguments to find a LocationLog
   * @example
   * // Get one LocationLog
   * const locationLog = await prisma.locationLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LocationLogFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, LocationLogFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__LocationLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more LocationLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocationLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LocationLogs
   * const locationLogs = await prisma.locationLog.findMany()
   *
   * // Get first 10 LocationLogs
   * const locationLogs = await prisma.locationLog.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const locationLogWithIdOnly = await prisma.locationLog.findMany({ select: { id: true } })
   *
   */
  findMany<T extends LocationLogFindManyArgs>(
    args?: Prisma.SelectSubset<T, LocationLogFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a LocationLog.
   * @param {LocationLogCreateArgs} args - Arguments to create a LocationLog.
   * @example
   * // Create one LocationLog
   * const LocationLog = await prisma.locationLog.create({
   *   data: {
   *     // ... data to create a LocationLog
   *   }
   * })
   *
   */
  create<T extends LocationLogCreateArgs>(
    args: Prisma.SelectSubset<T, LocationLogCreateArgs<ExtArgs>>
  ): Prisma.Prisma__LocationLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many LocationLogs.
   * @param {LocationLogCreateManyArgs} args - Arguments to create many LocationLogs.
   * @example
   * // Create many LocationLogs
   * const locationLog = await prisma.locationLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends LocationLogCreateManyArgs>(
    args?: Prisma.SelectSubset<T, LocationLogCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many LocationLogs and returns the data saved in the database.
   * @param {LocationLogCreateManyAndReturnArgs} args - Arguments to create many LocationLogs.
   * @example
   * // Create many LocationLogs
   * const locationLog = await prisma.locationLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many LocationLogs and only return the `id`
   * const locationLogWithIdOnly = await prisma.locationLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends LocationLogCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, LocationLogCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a LocationLog.
   * @param {LocationLogDeleteArgs} args - Arguments to delete one LocationLog.
   * @example
   * // Delete one LocationLog
   * const LocationLog = await prisma.locationLog.delete({
   *   where: {
   *     // ... filter to delete one LocationLog
   *   }
   * })
   *
   */
  delete<T extends LocationLogDeleteArgs>(
    args: Prisma.SelectSubset<T, LocationLogDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__LocationLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one LocationLog.
   * @param {LocationLogUpdateArgs} args - Arguments to update one LocationLog.
   * @example
   * // Update one LocationLog
   * const locationLog = await prisma.locationLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends LocationLogUpdateArgs>(
    args: Prisma.SelectSubset<T, LocationLogUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__LocationLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more LocationLogs.
   * @param {LocationLogDeleteManyArgs} args - Arguments to filter LocationLogs to delete.
   * @example
   * // Delete a few LocationLogs
   * const { count } = await prisma.locationLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends LocationLogDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, LocationLogDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more LocationLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocationLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LocationLogs
   * const locationLog = await prisma.locationLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends LocationLogUpdateManyArgs>(
    args: Prisma.SelectSubset<T, LocationLogUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more LocationLogs and returns the data updated in the database.
   * @param {LocationLogUpdateManyAndReturnArgs} args - Arguments to update many LocationLogs.
   * @example
   * // Update many LocationLogs
   * const locationLog = await prisma.locationLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more LocationLogs and only return the `id`
   * const locationLogWithIdOnly = await prisma.locationLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends LocationLogUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, LocationLogUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one LocationLog.
   * @param {LocationLogUpsertArgs} args - Arguments to update or create a LocationLog.
   * @example
   * // Update or create a LocationLog
   * const locationLog = await prisma.locationLog.upsert({
   *   create: {
   *     // ... data to create a LocationLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LocationLog we want to update
   *   }
   * })
   */
  upsert<T extends LocationLogUpsertArgs>(
    args: Prisma.SelectSubset<T, LocationLogUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__LocationLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$LocationLogPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of LocationLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocationLogCountArgs} args - Arguments to filter LocationLogs to count.
   * @example
   * // Count the number of LocationLogs
   * const count = await prisma.locationLog.count({
   *   where: {
   *     // ... the filter for the LocationLogs we want to count
   *   }
   * })
   **/
  count<T extends LocationLogCountArgs>(
    args?: Prisma.Subset<T, LocationLogCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LocationLogCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a LocationLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocationLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends LocationLogAggregateArgs>(
    args: Prisma.Subset<T, LocationLogAggregateArgs>
  ): Prisma.PrismaPromise<GetLocationLogAggregateType<T>>;

  /**
   * Group by LocationLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocationLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends LocationLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LocationLogGroupByArgs['orderBy'] }
      : { orderBy?: LocationLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, LocationLogGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetLocationLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the LocationLog model
   */
  readonly fields: LocationLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LocationLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LocationLogClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  vehicle<T extends Prisma.VehicleInfoDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.VehicleInfoDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleInfoClient<
    | runtime.Types.Result.GetResult<
        Prisma.$VehicleInfoPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the LocationLog model
 */
export interface LocationLogFieldRefs {
  readonly id: Prisma.FieldRef<'LocationLog', 'String'>;
  readonly imei: Prisma.FieldRef<'LocationLog', 'String'>;
  readonly lat: Prisma.FieldRef<'LocationLog', 'Decimal'>;
  readonly lng: Prisma.FieldRef<'LocationLog', 'Decimal'>;
  readonly altitude: Prisma.FieldRef<'LocationLog', 'Decimal'>;
  readonly speed: Prisma.FieldRef<'LocationLog', 'Decimal'>;
  readonly heading: Prisma.FieldRef<'LocationLog', 'Decimal'>;
  readonly batteryVoltage: Prisma.FieldRef<'LocationLog', 'Float'>;
  readonly ignition: Prisma.FieldRef<'LocationLog', 'Boolean'>;
  readonly timestamp: Prisma.FieldRef<'LocationLog', 'DateTime'>;
  readonly createdAt: Prisma.FieldRef<'LocationLog', 'DateTime'>;
}

// Custom InputTypes
/**
 * LocationLog findUnique
 */
export type LocationLogFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * Filter, which LocationLog to fetch.
   */
  where: Prisma.LocationLogWhereUniqueInput;
};

/**
 * LocationLog findUniqueOrThrow
 */
export type LocationLogFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * Filter, which LocationLog to fetch.
   */
  where: Prisma.LocationLogWhereUniqueInput;
};

/**
 * LocationLog findFirst
 */
export type LocationLogFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * Filter, which LocationLog to fetch.
   */
  where?: Prisma.LocationLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of LocationLogs to fetch.
   */
  orderBy?:
    | Prisma.LocationLogOrderByWithRelationInput
    | Prisma.LocationLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for LocationLogs.
   */
  cursor?: Prisma.LocationLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` LocationLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` LocationLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of LocationLogs.
   */
  distinct?: Prisma.LocationLogScalarFieldEnum | Prisma.LocationLogScalarFieldEnum[];
};

/**
 * LocationLog findFirstOrThrow
 */
export type LocationLogFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * Filter, which LocationLog to fetch.
   */
  where?: Prisma.LocationLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of LocationLogs to fetch.
   */
  orderBy?:
    | Prisma.LocationLogOrderByWithRelationInput
    | Prisma.LocationLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for LocationLogs.
   */
  cursor?: Prisma.LocationLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` LocationLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` LocationLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of LocationLogs.
   */
  distinct?: Prisma.LocationLogScalarFieldEnum | Prisma.LocationLogScalarFieldEnum[];
};

/**
 * LocationLog findMany
 */
export type LocationLogFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * Filter, which LocationLogs to fetch.
   */
  where?: Prisma.LocationLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of LocationLogs to fetch.
   */
  orderBy?:
    | Prisma.LocationLogOrderByWithRelationInput
    | Prisma.LocationLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing LocationLogs.
   */
  cursor?: Prisma.LocationLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` LocationLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` LocationLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of LocationLogs.
   */
  distinct?: Prisma.LocationLogScalarFieldEnum | Prisma.LocationLogScalarFieldEnum[];
};

/**
 * LocationLog create
 */
export type LocationLogCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * The data needed to create a LocationLog.
   */
  data: Prisma.XOR<Prisma.LocationLogCreateInput, Prisma.LocationLogUncheckedCreateInput>;
};

/**
 * LocationLog createMany
 */
export type LocationLogCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many LocationLogs.
   */
  data: Prisma.LocationLogCreateManyInput | Prisma.LocationLogCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * LocationLog createManyAndReturn
 */
export type LocationLogCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * The data used to create many LocationLogs.
   */
  data: Prisma.LocationLogCreateManyInput | Prisma.LocationLogCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * LocationLog update
 */
export type LocationLogUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * The data needed to update a LocationLog.
   */
  data: Prisma.XOR<Prisma.LocationLogUpdateInput, Prisma.LocationLogUncheckedUpdateInput>;
  /**
   * Choose, which LocationLog to update.
   */
  where: Prisma.LocationLogWhereUniqueInput;
};

/**
 * LocationLog updateMany
 */
export type LocationLogUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update LocationLogs.
   */
  data: Prisma.XOR<
    Prisma.LocationLogUpdateManyMutationInput,
    Prisma.LocationLogUncheckedUpdateManyInput
  >;
  /**
   * Filter which LocationLogs to update
   */
  where?: Prisma.LocationLogWhereInput;
  /**
   * Limit how many LocationLogs to update.
   */
  limit?: number;
};

/**
 * LocationLog updateManyAndReturn
 */
export type LocationLogUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * The data used to update LocationLogs.
   */
  data: Prisma.XOR<
    Prisma.LocationLogUpdateManyMutationInput,
    Prisma.LocationLogUncheckedUpdateManyInput
  >;
  /**
   * Filter which LocationLogs to update
   */
  where?: Prisma.LocationLogWhereInput;
  /**
   * Limit how many LocationLogs to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * LocationLog upsert
 */
export type LocationLogUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * The filter to search for the LocationLog to update in case it exists.
   */
  where: Prisma.LocationLogWhereUniqueInput;
  /**
   * In case the LocationLog found by the `where` argument doesn't exist, create a new LocationLog with this data.
   */
  create: Prisma.XOR<Prisma.LocationLogCreateInput, Prisma.LocationLogUncheckedCreateInput>;
  /**
   * In case the LocationLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LocationLogUpdateInput, Prisma.LocationLogUncheckedUpdateInput>;
};

/**
 * LocationLog delete
 */
export type LocationLogDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
  /**
   * Filter which LocationLog to delete.
   */
  where: Prisma.LocationLogWhereUniqueInput;
};

/**
 * LocationLog deleteMany
 */
export type LocationLogDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which LocationLogs to delete
   */
  where?: Prisma.LocationLogWhereInput;
  /**
   * Limit how many LocationLogs to delete.
   */
  limit?: number;
};

/**
 * LocationLog without action
 */
export type LocationLogDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null;
};
