
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VehicleInfo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model VehicleInfo
 * 
 */
export type VehicleInfoModel = runtime.Types.Result.DefaultSelection<Prisma.$VehicleInfoPayload>

export type AggregateVehicleInfo = {
  _count: VehicleInfoCountAggregateOutputType | null
  _min: VehicleInfoMinAggregateOutputType | null
  _max: VehicleInfoMaxAggregateOutputType | null
}

export type VehicleInfoMinAggregateOutputType = {
  id: string | null
  imei: string | null
  vechicleNumb: string | null
  customerId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VehicleInfoMaxAggregateOutputType = {
  id: string | null
  imei: string | null
  vechicleNumb: string | null
  customerId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VehicleInfoCountAggregateOutputType = {
  id: number
  imei: number
  vechicleNumb: number
  customerId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type VehicleInfoMinAggregateInputType = {
  id?: true
  imei?: true
  vechicleNumb?: true
  customerId?: true
  createdAt?: true
  updatedAt?: true
}

export type VehicleInfoMaxAggregateInputType = {
  id?: true
  imei?: true
  vechicleNumb?: true
  customerId?: true
  createdAt?: true
  updatedAt?: true
}

export type VehicleInfoCountAggregateInputType = {
  id?: true
  imei?: true
  vechicleNumb?: true
  customerId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type VehicleInfoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VehicleInfo to aggregate.
   */
  where?: Prisma.VehicleInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VehicleInfos to fetch.
   */
  orderBy?: Prisma.VehicleInfoOrderByWithRelationInput | Prisma.VehicleInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VehicleInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VehicleInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VehicleInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VehicleInfos
  **/
  _count?: true | VehicleInfoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VehicleInfoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VehicleInfoMaxAggregateInputType
}

export type GetVehicleInfoAggregateType<T extends VehicleInfoAggregateArgs> = {
      [P in keyof T & keyof AggregateVehicleInfo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVehicleInfo[P]>
    : Prisma.GetScalarType<T[P], AggregateVehicleInfo[P]>
}




export type VehicleInfoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VehicleInfoWhereInput
  orderBy?: Prisma.VehicleInfoOrderByWithAggregationInput | Prisma.VehicleInfoOrderByWithAggregationInput[]
  by: Prisma.VehicleInfoScalarFieldEnum[] | Prisma.VehicleInfoScalarFieldEnum
  having?: Prisma.VehicleInfoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VehicleInfoCountAggregateInputType | true
  _min?: VehicleInfoMinAggregateInputType
  _max?: VehicleInfoMaxAggregateInputType
}

export type VehicleInfoGroupByOutputType = {
  id: string
  imei: string
  vechicleNumb: string
  customerId: string
  createdAt: Date
  updatedAt: Date
  _count: VehicleInfoCountAggregateOutputType | null
  _min: VehicleInfoMinAggregateOutputType | null
  _max: VehicleInfoMaxAggregateOutputType | null
}

type GetVehicleInfoGroupByPayload<T extends VehicleInfoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VehicleInfoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VehicleInfoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VehicleInfoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VehicleInfoGroupByOutputType[P]>
      }
    >
  >



export type VehicleInfoWhereInput = {
  AND?: Prisma.VehicleInfoWhereInput | Prisma.VehicleInfoWhereInput[]
  OR?: Prisma.VehicleInfoWhereInput[]
  NOT?: Prisma.VehicleInfoWhereInput | Prisma.VehicleInfoWhereInput[]
  id?: Prisma.UuidFilter<"VehicleInfo"> | string
  imei?: Prisma.StringFilter<"VehicleInfo"> | string
  vechicleNumb?: Prisma.StringFilter<"VehicleInfo"> | string
  customerId?: Prisma.StringFilter<"VehicleInfo"> | string
  createdAt?: Prisma.DateTimeFilter<"VehicleInfo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VehicleInfo"> | Date | string
  customer?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  locations?: Prisma.LocationLogListRelationFilter
  compliances?: Prisma.VehicleComplianceListRelationFilter
  geofech?: Prisma.GeofenceListRelationFilter
}

export type VehicleInfoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  imei?: Prisma.SortOrder
  vechicleNumb?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  customer?: Prisma.UserOrderByWithRelationInput
  locations?: Prisma.LocationLogOrderByRelationAggregateInput
  compliances?: Prisma.VehicleComplianceOrderByRelationAggregateInput
  geofech?: Prisma.GeofenceOrderByRelationAggregateInput
}

export type VehicleInfoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  imei?: string
  vechicleNumb?: string
  AND?: Prisma.VehicleInfoWhereInput | Prisma.VehicleInfoWhereInput[]
  OR?: Prisma.VehicleInfoWhereInput[]
  NOT?: Prisma.VehicleInfoWhereInput | Prisma.VehicleInfoWhereInput[]
  customerId?: Prisma.StringFilter<"VehicleInfo"> | string
  createdAt?: Prisma.DateTimeFilter<"VehicleInfo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VehicleInfo"> | Date | string
  customer?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  locations?: Prisma.LocationLogListRelationFilter
  compliances?: Prisma.VehicleComplianceListRelationFilter
  geofech?: Prisma.GeofenceListRelationFilter
}, "id" | "imei" | "vechicleNumb">

export type VehicleInfoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  imei?: Prisma.SortOrder
  vechicleNumb?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VehicleInfoCountOrderByAggregateInput
  _max?: Prisma.VehicleInfoMaxOrderByAggregateInput
  _min?: Prisma.VehicleInfoMinOrderByAggregateInput
}

export type VehicleInfoScalarWhereWithAggregatesInput = {
  AND?: Prisma.VehicleInfoScalarWhereWithAggregatesInput | Prisma.VehicleInfoScalarWhereWithAggregatesInput[]
  OR?: Prisma.VehicleInfoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VehicleInfoScalarWhereWithAggregatesInput | Prisma.VehicleInfoScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"VehicleInfo"> | string
  imei?: Prisma.StringWithAggregatesFilter<"VehicleInfo"> | string
  vechicleNumb?: Prisma.StringWithAggregatesFilter<"VehicleInfo"> | string
  customerId?: Prisma.StringWithAggregatesFilter<"VehicleInfo"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VehicleInfo"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VehicleInfo"> | Date | string
}

export type VehicleInfoCreateInput = {
  id?: string
  imei: string
  vechicleNumb: string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.UserCreateNestedOneWithoutVehicleInfosInput
  locations?: Prisma.LocationLogCreateNestedManyWithoutVehicleInput
  compliances?: Prisma.VehicleComplianceCreateNestedManyWithoutVehicleInput
  geofech?: Prisma.GeofenceCreateNestedManyWithoutVehiclesInput
}

export type VehicleInfoUncheckedCreateInput = {
  id?: string
  imei: string
  vechicleNumb: string
  customerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  locations?: Prisma.LocationLogUncheckedCreateNestedManyWithoutVehicleInput
  compliances?: Prisma.VehicleComplianceUncheckedCreateNestedManyWithoutVehicleInput
  geofech?: Prisma.GeofenceUncheckedCreateNestedManyWithoutVehiclesInput
}

export type VehicleInfoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.UserUpdateOneRequiredWithoutVehicleInfosNestedInput
  locations?: Prisma.LocationLogUpdateManyWithoutVehicleNestedInput
  compliances?: Prisma.VehicleComplianceUpdateManyWithoutVehicleNestedInput
  geofech?: Prisma.GeofenceUpdateManyWithoutVehiclesNestedInput
}

export type VehicleInfoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  locations?: Prisma.LocationLogUncheckedUpdateManyWithoutVehicleNestedInput
  compliances?: Prisma.VehicleComplianceUncheckedUpdateManyWithoutVehicleNestedInput
  geofech?: Prisma.GeofenceUncheckedUpdateManyWithoutVehiclesNestedInput
}

export type VehicleInfoCreateManyInput = {
  id?: string
  imei: string
  vechicleNumb: string
  customerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VehicleInfoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VehicleInfoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VehicleInfoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  imei?: Prisma.SortOrder
  vechicleNumb?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VehicleInfoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  imei?: Prisma.SortOrder
  vechicleNumb?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VehicleInfoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  imei?: Prisma.SortOrder
  vechicleNumb?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VehicleInfoScalarRelationFilter = {
  is?: Prisma.VehicleInfoWhereInput
  isNot?: Prisma.VehicleInfoWhereInput
}

export type VehicleInfoListRelationFilter = {
  every?: Prisma.VehicleInfoWhereInput
  some?: Prisma.VehicleInfoWhereInput
  none?: Prisma.VehicleInfoWhereInput
}

export type VehicleInfoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type VehicleInfoCreateNestedOneWithoutLocationsInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutLocationsInput, Prisma.VehicleInfoUncheckedCreateWithoutLocationsInput>
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutLocationsInput
  connect?: Prisma.VehicleInfoWhereUniqueInput
}

export type VehicleInfoUpdateOneRequiredWithoutLocationsNestedInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutLocationsInput, Prisma.VehicleInfoUncheckedCreateWithoutLocationsInput>
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutLocationsInput
  upsert?: Prisma.VehicleInfoUpsertWithoutLocationsInput
  connect?: Prisma.VehicleInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VehicleInfoUpdateToOneWithWhereWithoutLocationsInput, Prisma.VehicleInfoUpdateWithoutLocationsInput>, Prisma.VehicleInfoUncheckedUpdateWithoutLocationsInput>
}

export type VehicleInfoCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCustomerInput, Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput> | Prisma.VehicleInfoCreateWithoutCustomerInput[] | Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutCustomerInput | Prisma.VehicleInfoCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.VehicleInfoCreateManyCustomerInputEnvelope
  connect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
}

export type VehicleInfoUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCustomerInput, Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput> | Prisma.VehicleInfoCreateWithoutCustomerInput[] | Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutCustomerInput | Prisma.VehicleInfoCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.VehicleInfoCreateManyCustomerInputEnvelope
  connect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
}

export type VehicleInfoUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCustomerInput, Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput> | Prisma.VehicleInfoCreateWithoutCustomerInput[] | Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutCustomerInput | Prisma.VehicleInfoCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.VehicleInfoUpsertWithWhereUniqueWithoutCustomerInput | Prisma.VehicleInfoUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.VehicleInfoCreateManyCustomerInputEnvelope
  set?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  disconnect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  delete?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  connect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  update?: Prisma.VehicleInfoUpdateWithWhereUniqueWithoutCustomerInput | Prisma.VehicleInfoUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.VehicleInfoUpdateManyWithWhereWithoutCustomerInput | Prisma.VehicleInfoUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.VehicleInfoScalarWhereInput | Prisma.VehicleInfoScalarWhereInput[]
}

export type VehicleInfoUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCustomerInput, Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput> | Prisma.VehicleInfoCreateWithoutCustomerInput[] | Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutCustomerInput | Prisma.VehicleInfoCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.VehicleInfoUpsertWithWhereUniqueWithoutCustomerInput | Prisma.VehicleInfoUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.VehicleInfoCreateManyCustomerInputEnvelope
  set?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  disconnect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  delete?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  connect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  update?: Prisma.VehicleInfoUpdateWithWhereUniqueWithoutCustomerInput | Prisma.VehicleInfoUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.VehicleInfoUpdateManyWithWhereWithoutCustomerInput | Prisma.VehicleInfoUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.VehicleInfoScalarWhereInput | Prisma.VehicleInfoScalarWhereInput[]
}

export type VehicleInfoCreateNestedManyWithoutGeofechInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutGeofechInput, Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput> | Prisma.VehicleInfoCreateWithoutGeofechInput[] | Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput[]
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutGeofechInput | Prisma.VehicleInfoCreateOrConnectWithoutGeofechInput[]
  connect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
}

export type VehicleInfoUncheckedCreateNestedManyWithoutGeofechInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutGeofechInput, Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput> | Prisma.VehicleInfoCreateWithoutGeofechInput[] | Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput[]
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutGeofechInput | Prisma.VehicleInfoCreateOrConnectWithoutGeofechInput[]
  connect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
}

export type VehicleInfoUpdateManyWithoutGeofechNestedInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutGeofechInput, Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput> | Prisma.VehicleInfoCreateWithoutGeofechInput[] | Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput[]
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutGeofechInput | Prisma.VehicleInfoCreateOrConnectWithoutGeofechInput[]
  upsert?: Prisma.VehicleInfoUpsertWithWhereUniqueWithoutGeofechInput | Prisma.VehicleInfoUpsertWithWhereUniqueWithoutGeofechInput[]
  set?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  disconnect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  delete?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  connect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  update?: Prisma.VehicleInfoUpdateWithWhereUniqueWithoutGeofechInput | Prisma.VehicleInfoUpdateWithWhereUniqueWithoutGeofechInput[]
  updateMany?: Prisma.VehicleInfoUpdateManyWithWhereWithoutGeofechInput | Prisma.VehicleInfoUpdateManyWithWhereWithoutGeofechInput[]
  deleteMany?: Prisma.VehicleInfoScalarWhereInput | Prisma.VehicleInfoScalarWhereInput[]
}

export type VehicleInfoUncheckedUpdateManyWithoutGeofechNestedInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutGeofechInput, Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput> | Prisma.VehicleInfoCreateWithoutGeofechInput[] | Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput[]
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutGeofechInput | Prisma.VehicleInfoCreateOrConnectWithoutGeofechInput[]
  upsert?: Prisma.VehicleInfoUpsertWithWhereUniqueWithoutGeofechInput | Prisma.VehicleInfoUpsertWithWhereUniqueWithoutGeofechInput[]
  set?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  disconnect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  delete?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  connect?: Prisma.VehicleInfoWhereUniqueInput | Prisma.VehicleInfoWhereUniqueInput[]
  update?: Prisma.VehicleInfoUpdateWithWhereUniqueWithoutGeofechInput | Prisma.VehicleInfoUpdateWithWhereUniqueWithoutGeofechInput[]
  updateMany?: Prisma.VehicleInfoUpdateManyWithWhereWithoutGeofechInput | Prisma.VehicleInfoUpdateManyWithWhereWithoutGeofechInput[]
  deleteMany?: Prisma.VehicleInfoScalarWhereInput | Prisma.VehicleInfoScalarWhereInput[]
}

export type VehicleInfoCreateNestedOneWithoutCompliancesInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCompliancesInput, Prisma.VehicleInfoUncheckedCreateWithoutCompliancesInput>
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutCompliancesInput
  connect?: Prisma.VehicleInfoWhereUniqueInput
}

export type VehicleInfoUpdateOneRequiredWithoutCompliancesNestedInput = {
  create?: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCompliancesInput, Prisma.VehicleInfoUncheckedCreateWithoutCompliancesInput>
  connectOrCreate?: Prisma.VehicleInfoCreateOrConnectWithoutCompliancesInput
  upsert?: Prisma.VehicleInfoUpsertWithoutCompliancesInput
  connect?: Prisma.VehicleInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VehicleInfoUpdateToOneWithWhereWithoutCompliancesInput, Prisma.VehicleInfoUpdateWithoutCompliancesInput>, Prisma.VehicleInfoUncheckedUpdateWithoutCompliancesInput>
}

export type VehicleInfoCreateWithoutLocationsInput = {
  id?: string
  imei: string
  vechicleNumb: string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.UserCreateNestedOneWithoutVehicleInfosInput
  compliances?: Prisma.VehicleComplianceCreateNestedManyWithoutVehicleInput
  geofech?: Prisma.GeofenceCreateNestedManyWithoutVehiclesInput
}

export type VehicleInfoUncheckedCreateWithoutLocationsInput = {
  id?: string
  imei: string
  vechicleNumb: string
  customerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  compliances?: Prisma.VehicleComplianceUncheckedCreateNestedManyWithoutVehicleInput
  geofech?: Prisma.GeofenceUncheckedCreateNestedManyWithoutVehiclesInput
}

export type VehicleInfoCreateOrConnectWithoutLocationsInput = {
  where: Prisma.VehicleInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.VehicleInfoCreateWithoutLocationsInput, Prisma.VehicleInfoUncheckedCreateWithoutLocationsInput>
}

export type VehicleInfoUpsertWithoutLocationsInput = {
  update: Prisma.XOR<Prisma.VehicleInfoUpdateWithoutLocationsInput, Prisma.VehicleInfoUncheckedUpdateWithoutLocationsInput>
  create: Prisma.XOR<Prisma.VehicleInfoCreateWithoutLocationsInput, Prisma.VehicleInfoUncheckedCreateWithoutLocationsInput>
  where?: Prisma.VehicleInfoWhereInput
}

export type VehicleInfoUpdateToOneWithWhereWithoutLocationsInput = {
  where?: Prisma.VehicleInfoWhereInput
  data: Prisma.XOR<Prisma.VehicleInfoUpdateWithoutLocationsInput, Prisma.VehicleInfoUncheckedUpdateWithoutLocationsInput>
}

export type VehicleInfoUpdateWithoutLocationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.UserUpdateOneRequiredWithoutVehicleInfosNestedInput
  compliances?: Prisma.VehicleComplianceUpdateManyWithoutVehicleNestedInput
  geofech?: Prisma.GeofenceUpdateManyWithoutVehiclesNestedInput
}

export type VehicleInfoUncheckedUpdateWithoutLocationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  compliances?: Prisma.VehicleComplianceUncheckedUpdateManyWithoutVehicleNestedInput
  geofech?: Prisma.GeofenceUncheckedUpdateManyWithoutVehiclesNestedInput
}

export type VehicleInfoCreateWithoutCustomerInput = {
  id?: string
  imei: string
  vechicleNumb: string
  createdAt?: Date | string
  updatedAt?: Date | string
  locations?: Prisma.LocationLogCreateNestedManyWithoutVehicleInput
  compliances?: Prisma.VehicleComplianceCreateNestedManyWithoutVehicleInput
  geofech?: Prisma.GeofenceCreateNestedManyWithoutVehiclesInput
}

export type VehicleInfoUncheckedCreateWithoutCustomerInput = {
  id?: string
  imei: string
  vechicleNumb: string
  createdAt?: Date | string
  updatedAt?: Date | string
  locations?: Prisma.LocationLogUncheckedCreateNestedManyWithoutVehicleInput
  compliances?: Prisma.VehicleComplianceUncheckedCreateNestedManyWithoutVehicleInput
  geofech?: Prisma.GeofenceUncheckedCreateNestedManyWithoutVehiclesInput
}

export type VehicleInfoCreateOrConnectWithoutCustomerInput = {
  where: Prisma.VehicleInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCustomerInput, Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput>
}

export type VehicleInfoCreateManyCustomerInputEnvelope = {
  data: Prisma.VehicleInfoCreateManyCustomerInput | Prisma.VehicleInfoCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type VehicleInfoUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.VehicleInfoWhereUniqueInput
  update: Prisma.XOR<Prisma.VehicleInfoUpdateWithoutCustomerInput, Prisma.VehicleInfoUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCustomerInput, Prisma.VehicleInfoUncheckedCreateWithoutCustomerInput>
}

export type VehicleInfoUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.VehicleInfoWhereUniqueInput
  data: Prisma.XOR<Prisma.VehicleInfoUpdateWithoutCustomerInput, Prisma.VehicleInfoUncheckedUpdateWithoutCustomerInput>
}

export type VehicleInfoUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.VehicleInfoScalarWhereInput
  data: Prisma.XOR<Prisma.VehicleInfoUpdateManyMutationInput, Prisma.VehicleInfoUncheckedUpdateManyWithoutCustomerInput>
}

export type VehicleInfoScalarWhereInput = {
  AND?: Prisma.VehicleInfoScalarWhereInput | Prisma.VehicleInfoScalarWhereInput[]
  OR?: Prisma.VehicleInfoScalarWhereInput[]
  NOT?: Prisma.VehicleInfoScalarWhereInput | Prisma.VehicleInfoScalarWhereInput[]
  id?: Prisma.UuidFilter<"VehicleInfo"> | string
  imei?: Prisma.StringFilter<"VehicleInfo"> | string
  vechicleNumb?: Prisma.StringFilter<"VehicleInfo"> | string
  customerId?: Prisma.StringFilter<"VehicleInfo"> | string
  createdAt?: Prisma.DateTimeFilter<"VehicleInfo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VehicleInfo"> | Date | string
}

export type VehicleInfoCreateWithoutGeofechInput = {
  id?: string
  imei: string
  vechicleNumb: string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.UserCreateNestedOneWithoutVehicleInfosInput
  locations?: Prisma.LocationLogCreateNestedManyWithoutVehicleInput
  compliances?: Prisma.VehicleComplianceCreateNestedManyWithoutVehicleInput
}

export type VehicleInfoUncheckedCreateWithoutGeofechInput = {
  id?: string
  imei: string
  vechicleNumb: string
  customerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  locations?: Prisma.LocationLogUncheckedCreateNestedManyWithoutVehicleInput
  compliances?: Prisma.VehicleComplianceUncheckedCreateNestedManyWithoutVehicleInput
}

export type VehicleInfoCreateOrConnectWithoutGeofechInput = {
  where: Prisma.VehicleInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.VehicleInfoCreateWithoutGeofechInput, Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput>
}

export type VehicleInfoUpsertWithWhereUniqueWithoutGeofechInput = {
  where: Prisma.VehicleInfoWhereUniqueInput
  update: Prisma.XOR<Prisma.VehicleInfoUpdateWithoutGeofechInput, Prisma.VehicleInfoUncheckedUpdateWithoutGeofechInput>
  create: Prisma.XOR<Prisma.VehicleInfoCreateWithoutGeofechInput, Prisma.VehicleInfoUncheckedCreateWithoutGeofechInput>
}

export type VehicleInfoUpdateWithWhereUniqueWithoutGeofechInput = {
  where: Prisma.VehicleInfoWhereUniqueInput
  data: Prisma.XOR<Prisma.VehicleInfoUpdateWithoutGeofechInput, Prisma.VehicleInfoUncheckedUpdateWithoutGeofechInput>
}

export type VehicleInfoUpdateManyWithWhereWithoutGeofechInput = {
  where: Prisma.VehicleInfoScalarWhereInput
  data: Prisma.XOR<Prisma.VehicleInfoUpdateManyMutationInput, Prisma.VehicleInfoUncheckedUpdateManyWithoutGeofechInput>
}

export type VehicleInfoCreateWithoutCompliancesInput = {
  id?: string
  imei: string
  vechicleNumb: string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.UserCreateNestedOneWithoutVehicleInfosInput
  locations?: Prisma.LocationLogCreateNestedManyWithoutVehicleInput
  geofech?: Prisma.GeofenceCreateNestedManyWithoutVehiclesInput
}

export type VehicleInfoUncheckedCreateWithoutCompliancesInput = {
  id?: string
  imei: string
  vechicleNumb: string
  customerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  locations?: Prisma.LocationLogUncheckedCreateNestedManyWithoutVehicleInput
  geofech?: Prisma.GeofenceUncheckedCreateNestedManyWithoutVehiclesInput
}

export type VehicleInfoCreateOrConnectWithoutCompliancesInput = {
  where: Prisma.VehicleInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCompliancesInput, Prisma.VehicleInfoUncheckedCreateWithoutCompliancesInput>
}

export type VehicleInfoUpsertWithoutCompliancesInput = {
  update: Prisma.XOR<Prisma.VehicleInfoUpdateWithoutCompliancesInput, Prisma.VehicleInfoUncheckedUpdateWithoutCompliancesInput>
  create: Prisma.XOR<Prisma.VehicleInfoCreateWithoutCompliancesInput, Prisma.VehicleInfoUncheckedCreateWithoutCompliancesInput>
  where?: Prisma.VehicleInfoWhereInput
}

export type VehicleInfoUpdateToOneWithWhereWithoutCompliancesInput = {
  where?: Prisma.VehicleInfoWhereInput
  data: Prisma.XOR<Prisma.VehicleInfoUpdateWithoutCompliancesInput, Prisma.VehicleInfoUncheckedUpdateWithoutCompliancesInput>
}

export type VehicleInfoUpdateWithoutCompliancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.UserUpdateOneRequiredWithoutVehicleInfosNestedInput
  locations?: Prisma.LocationLogUpdateManyWithoutVehicleNestedInput
  geofech?: Prisma.GeofenceUpdateManyWithoutVehiclesNestedInput
}

export type VehicleInfoUncheckedUpdateWithoutCompliancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  locations?: Prisma.LocationLogUncheckedUpdateManyWithoutVehicleNestedInput
  geofech?: Prisma.GeofenceUncheckedUpdateManyWithoutVehiclesNestedInput
}

export type VehicleInfoCreateManyCustomerInput = {
  id?: string
  imei: string
  vechicleNumb: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VehicleInfoUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  locations?: Prisma.LocationLogUpdateManyWithoutVehicleNestedInput
  compliances?: Prisma.VehicleComplianceUpdateManyWithoutVehicleNestedInput
  geofech?: Prisma.GeofenceUpdateManyWithoutVehiclesNestedInput
}

export type VehicleInfoUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  locations?: Prisma.LocationLogUncheckedUpdateManyWithoutVehicleNestedInput
  compliances?: Prisma.VehicleComplianceUncheckedUpdateManyWithoutVehicleNestedInput
  geofech?: Prisma.GeofenceUncheckedUpdateManyWithoutVehiclesNestedInput
}

export type VehicleInfoUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VehicleInfoUpdateWithoutGeofechInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.UserUpdateOneRequiredWithoutVehicleInfosNestedInput
  locations?: Prisma.LocationLogUpdateManyWithoutVehicleNestedInput
  compliances?: Prisma.VehicleComplianceUpdateManyWithoutVehicleNestedInput
}

export type VehicleInfoUncheckedUpdateWithoutGeofechInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  locations?: Prisma.LocationLogUncheckedUpdateManyWithoutVehicleNestedInput
  compliances?: Prisma.VehicleComplianceUncheckedUpdateManyWithoutVehicleNestedInput
}

export type VehicleInfoUncheckedUpdateManyWithoutGeofechInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imei?: Prisma.StringFieldUpdateOperationsInput | string
  vechicleNumb?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type VehicleInfoCountOutputType
 */

export type VehicleInfoCountOutputType = {
  locations: number
  compliances: number
  geofech: number
}

export type VehicleInfoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  locations?: boolean | VehicleInfoCountOutputTypeCountLocationsArgs
  compliances?: boolean | VehicleInfoCountOutputTypeCountCompliancesArgs
  geofech?: boolean | VehicleInfoCountOutputTypeCountGeofechArgs
}

/**
 * VehicleInfoCountOutputType without action
 */
export type VehicleInfoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfoCountOutputType
   */
  select?: Prisma.VehicleInfoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VehicleInfoCountOutputType without action
 */
export type VehicleInfoCountOutputTypeCountLocationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LocationLogWhereInput
}

/**
 * VehicleInfoCountOutputType without action
 */
export type VehicleInfoCountOutputTypeCountCompliancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VehicleComplianceWhereInput
}

/**
 * VehicleInfoCountOutputType without action
 */
export type VehicleInfoCountOutputTypeCountGeofechArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GeofenceWhereInput
}


export type VehicleInfoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  imei?: boolean
  vechicleNumb?: boolean
  customerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  locations?: boolean | Prisma.VehicleInfo$locationsArgs<ExtArgs>
  compliances?: boolean | Prisma.VehicleInfo$compliancesArgs<ExtArgs>
  geofech?: boolean | Prisma.VehicleInfo$geofechArgs<ExtArgs>
  _count?: boolean | Prisma.VehicleInfoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vehicleInfo"]>

export type VehicleInfoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  imei?: boolean
  vechicleNumb?: boolean
  customerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vehicleInfo"]>

export type VehicleInfoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  imei?: boolean
  vechicleNumb?: boolean
  customerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vehicleInfo"]>

export type VehicleInfoSelectScalar = {
  id?: boolean
  imei?: boolean
  vechicleNumb?: boolean
  customerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type VehicleInfoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "imei" | "vechicleNumb" | "customerId" | "createdAt" | "updatedAt", ExtArgs["result"]["vehicleInfo"]>
export type VehicleInfoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  locations?: boolean | Prisma.VehicleInfo$locationsArgs<ExtArgs>
  compliances?: boolean | Prisma.VehicleInfo$compliancesArgs<ExtArgs>
  geofech?: boolean | Prisma.VehicleInfo$geofechArgs<ExtArgs>
  _count?: boolean | Prisma.VehicleInfoCountOutputTypeDefaultArgs<ExtArgs>
}
export type VehicleInfoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type VehicleInfoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $VehicleInfoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VehicleInfo"
  objects: {
    customer: Prisma.$UserPayload<ExtArgs>
    locations: Prisma.$LocationLogPayload<ExtArgs>[]
    compliances: Prisma.$VehicleCompliancePayload<ExtArgs>[]
    geofech: Prisma.$GeofencePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    imei: string
    vechicleNumb: string
    customerId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["vehicleInfo"]>
  composites: {}
}

export type VehicleInfoGetPayload<S extends boolean | null | undefined | VehicleInfoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload, S>

export type VehicleInfoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VehicleInfoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VehicleInfoCountAggregateInputType | true
  }

export interface VehicleInfoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VehicleInfo'], meta: { name: 'VehicleInfo' } }
  /**
   * Find zero or one VehicleInfo that matches the filter.
   * @param {VehicleInfoFindUniqueArgs} args - Arguments to find a VehicleInfo
   * @example
   * // Get one VehicleInfo
   * const vehicleInfo = await prisma.vehicleInfo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VehicleInfoFindUniqueArgs>(args: Prisma.SelectSubset<T, VehicleInfoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VehicleInfoClient<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VehicleInfo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VehicleInfoFindUniqueOrThrowArgs} args - Arguments to find a VehicleInfo
   * @example
   * // Get one VehicleInfo
   * const vehicleInfo = await prisma.vehicleInfo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VehicleInfoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VehicleInfoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VehicleInfoClient<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VehicleInfo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleInfoFindFirstArgs} args - Arguments to find a VehicleInfo
   * @example
   * // Get one VehicleInfo
   * const vehicleInfo = await prisma.vehicleInfo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VehicleInfoFindFirstArgs>(args?: Prisma.SelectSubset<T, VehicleInfoFindFirstArgs<ExtArgs>>): Prisma.Prisma__VehicleInfoClient<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VehicleInfo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleInfoFindFirstOrThrowArgs} args - Arguments to find a VehicleInfo
   * @example
   * // Get one VehicleInfo
   * const vehicleInfo = await prisma.vehicleInfo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VehicleInfoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VehicleInfoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VehicleInfoClient<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VehicleInfos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleInfoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VehicleInfos
   * const vehicleInfos = await prisma.vehicleInfo.findMany()
   * 
   * // Get first 10 VehicleInfos
   * const vehicleInfos = await prisma.vehicleInfo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vehicleInfoWithIdOnly = await prisma.vehicleInfo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VehicleInfoFindManyArgs>(args?: Prisma.SelectSubset<T, VehicleInfoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VehicleInfo.
   * @param {VehicleInfoCreateArgs} args - Arguments to create a VehicleInfo.
   * @example
   * // Create one VehicleInfo
   * const VehicleInfo = await prisma.vehicleInfo.create({
   *   data: {
   *     // ... data to create a VehicleInfo
   *   }
   * })
   * 
   */
  create<T extends VehicleInfoCreateArgs>(args: Prisma.SelectSubset<T, VehicleInfoCreateArgs<ExtArgs>>): Prisma.Prisma__VehicleInfoClient<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VehicleInfos.
   * @param {VehicleInfoCreateManyArgs} args - Arguments to create many VehicleInfos.
   * @example
   * // Create many VehicleInfos
   * const vehicleInfo = await prisma.vehicleInfo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VehicleInfoCreateManyArgs>(args?: Prisma.SelectSubset<T, VehicleInfoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VehicleInfos and returns the data saved in the database.
   * @param {VehicleInfoCreateManyAndReturnArgs} args - Arguments to create many VehicleInfos.
   * @example
   * // Create many VehicleInfos
   * const vehicleInfo = await prisma.vehicleInfo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VehicleInfos and only return the `id`
   * const vehicleInfoWithIdOnly = await prisma.vehicleInfo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VehicleInfoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VehicleInfoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VehicleInfo.
   * @param {VehicleInfoDeleteArgs} args - Arguments to delete one VehicleInfo.
   * @example
   * // Delete one VehicleInfo
   * const VehicleInfo = await prisma.vehicleInfo.delete({
   *   where: {
   *     // ... filter to delete one VehicleInfo
   *   }
   * })
   * 
   */
  delete<T extends VehicleInfoDeleteArgs>(args: Prisma.SelectSubset<T, VehicleInfoDeleteArgs<ExtArgs>>): Prisma.Prisma__VehicleInfoClient<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VehicleInfo.
   * @param {VehicleInfoUpdateArgs} args - Arguments to update one VehicleInfo.
   * @example
   * // Update one VehicleInfo
   * const vehicleInfo = await prisma.vehicleInfo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VehicleInfoUpdateArgs>(args: Prisma.SelectSubset<T, VehicleInfoUpdateArgs<ExtArgs>>): Prisma.Prisma__VehicleInfoClient<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VehicleInfos.
   * @param {VehicleInfoDeleteManyArgs} args - Arguments to filter VehicleInfos to delete.
   * @example
   * // Delete a few VehicleInfos
   * const { count } = await prisma.vehicleInfo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VehicleInfoDeleteManyArgs>(args?: Prisma.SelectSubset<T, VehicleInfoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VehicleInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleInfoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VehicleInfos
   * const vehicleInfo = await prisma.vehicleInfo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VehicleInfoUpdateManyArgs>(args: Prisma.SelectSubset<T, VehicleInfoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VehicleInfos and returns the data updated in the database.
   * @param {VehicleInfoUpdateManyAndReturnArgs} args - Arguments to update many VehicleInfos.
   * @example
   * // Update many VehicleInfos
   * const vehicleInfo = await prisma.vehicleInfo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VehicleInfos and only return the `id`
   * const vehicleInfoWithIdOnly = await prisma.vehicleInfo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VehicleInfoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VehicleInfoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VehicleInfo.
   * @param {VehicleInfoUpsertArgs} args - Arguments to update or create a VehicleInfo.
   * @example
   * // Update or create a VehicleInfo
   * const vehicleInfo = await prisma.vehicleInfo.upsert({
   *   create: {
   *     // ... data to create a VehicleInfo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VehicleInfo we want to update
   *   }
   * })
   */
  upsert<T extends VehicleInfoUpsertArgs>(args: Prisma.SelectSubset<T, VehicleInfoUpsertArgs<ExtArgs>>): Prisma.Prisma__VehicleInfoClient<runtime.Types.Result.GetResult<Prisma.$VehicleInfoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VehicleInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleInfoCountArgs} args - Arguments to filter VehicleInfos to count.
   * @example
   * // Count the number of VehicleInfos
   * const count = await prisma.vehicleInfo.count({
   *   where: {
   *     // ... the filter for the VehicleInfos we want to count
   *   }
   * })
  **/
  count<T extends VehicleInfoCountArgs>(
    args?: Prisma.Subset<T, VehicleInfoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VehicleInfoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VehicleInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleInfoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VehicleInfoAggregateArgs>(args: Prisma.Subset<T, VehicleInfoAggregateArgs>): Prisma.PrismaPromise<GetVehicleInfoAggregateType<T>>

  /**
   * Group by VehicleInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleInfoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VehicleInfoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VehicleInfoGroupByArgs['orderBy'] }
      : { orderBy?: VehicleInfoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VehicleInfoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVehicleInfoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VehicleInfo model
 */
readonly fields: VehicleInfoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VehicleInfo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VehicleInfoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  customer<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  locations<T extends Prisma.VehicleInfo$locationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VehicleInfo$locationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LocationLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  compliances<T extends Prisma.VehicleInfo$compliancesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VehicleInfo$compliancesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VehicleCompliancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  geofech<T extends Prisma.VehicleInfo$geofechArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VehicleInfo$geofechArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GeofencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VehicleInfo model
 */
export interface VehicleInfoFieldRefs {
  readonly id: Prisma.FieldRef<"VehicleInfo", 'String'>
  readonly imei: Prisma.FieldRef<"VehicleInfo", 'String'>
  readonly vechicleNumb: Prisma.FieldRef<"VehicleInfo", 'String'>
  readonly customerId: Prisma.FieldRef<"VehicleInfo", 'String'>
  readonly createdAt: Prisma.FieldRef<"VehicleInfo", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VehicleInfo", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VehicleInfo findUnique
 */
export type VehicleInfoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * Filter, which VehicleInfo to fetch.
   */
  where: Prisma.VehicleInfoWhereUniqueInput
}

/**
 * VehicleInfo findUniqueOrThrow
 */
export type VehicleInfoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * Filter, which VehicleInfo to fetch.
   */
  where: Prisma.VehicleInfoWhereUniqueInput
}

/**
 * VehicleInfo findFirst
 */
export type VehicleInfoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * Filter, which VehicleInfo to fetch.
   */
  where?: Prisma.VehicleInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VehicleInfos to fetch.
   */
  orderBy?: Prisma.VehicleInfoOrderByWithRelationInput | Prisma.VehicleInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VehicleInfos.
   */
  cursor?: Prisma.VehicleInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VehicleInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VehicleInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VehicleInfos.
   */
  distinct?: Prisma.VehicleInfoScalarFieldEnum | Prisma.VehicleInfoScalarFieldEnum[]
}

/**
 * VehicleInfo findFirstOrThrow
 */
export type VehicleInfoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * Filter, which VehicleInfo to fetch.
   */
  where?: Prisma.VehicleInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VehicleInfos to fetch.
   */
  orderBy?: Prisma.VehicleInfoOrderByWithRelationInput | Prisma.VehicleInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VehicleInfos.
   */
  cursor?: Prisma.VehicleInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VehicleInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VehicleInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VehicleInfos.
   */
  distinct?: Prisma.VehicleInfoScalarFieldEnum | Prisma.VehicleInfoScalarFieldEnum[]
}

/**
 * VehicleInfo findMany
 */
export type VehicleInfoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * Filter, which VehicleInfos to fetch.
   */
  where?: Prisma.VehicleInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VehicleInfos to fetch.
   */
  orderBy?: Prisma.VehicleInfoOrderByWithRelationInput | Prisma.VehicleInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VehicleInfos.
   */
  cursor?: Prisma.VehicleInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VehicleInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VehicleInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VehicleInfos.
   */
  distinct?: Prisma.VehicleInfoScalarFieldEnum | Prisma.VehicleInfoScalarFieldEnum[]
}

/**
 * VehicleInfo create
 */
export type VehicleInfoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * The data needed to create a VehicleInfo.
   */
  data: Prisma.XOR<Prisma.VehicleInfoCreateInput, Prisma.VehicleInfoUncheckedCreateInput>
}

/**
 * VehicleInfo createMany
 */
export type VehicleInfoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VehicleInfos.
   */
  data: Prisma.VehicleInfoCreateManyInput | Prisma.VehicleInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VehicleInfo createManyAndReturn
 */
export type VehicleInfoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * The data used to create many VehicleInfos.
   */
  data: Prisma.VehicleInfoCreateManyInput | Prisma.VehicleInfoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VehicleInfo update
 */
export type VehicleInfoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * The data needed to update a VehicleInfo.
   */
  data: Prisma.XOR<Prisma.VehicleInfoUpdateInput, Prisma.VehicleInfoUncheckedUpdateInput>
  /**
   * Choose, which VehicleInfo to update.
   */
  where: Prisma.VehicleInfoWhereUniqueInput
}

/**
 * VehicleInfo updateMany
 */
export type VehicleInfoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VehicleInfos.
   */
  data: Prisma.XOR<Prisma.VehicleInfoUpdateManyMutationInput, Prisma.VehicleInfoUncheckedUpdateManyInput>
  /**
   * Filter which VehicleInfos to update
   */
  where?: Prisma.VehicleInfoWhereInput
  /**
   * Limit how many VehicleInfos to update.
   */
  limit?: number
}

/**
 * VehicleInfo updateManyAndReturn
 */
export type VehicleInfoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * The data used to update VehicleInfos.
   */
  data: Prisma.XOR<Prisma.VehicleInfoUpdateManyMutationInput, Prisma.VehicleInfoUncheckedUpdateManyInput>
  /**
   * Filter which VehicleInfos to update
   */
  where?: Prisma.VehicleInfoWhereInput
  /**
   * Limit how many VehicleInfos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VehicleInfo upsert
 */
export type VehicleInfoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * The filter to search for the VehicleInfo to update in case it exists.
   */
  where: Prisma.VehicleInfoWhereUniqueInput
  /**
   * In case the VehicleInfo found by the `where` argument doesn't exist, create a new VehicleInfo with this data.
   */
  create: Prisma.XOR<Prisma.VehicleInfoCreateInput, Prisma.VehicleInfoUncheckedCreateInput>
  /**
   * In case the VehicleInfo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VehicleInfoUpdateInput, Prisma.VehicleInfoUncheckedUpdateInput>
}

/**
 * VehicleInfo delete
 */
export type VehicleInfoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
  /**
   * Filter which VehicleInfo to delete.
   */
  where: Prisma.VehicleInfoWhereUniqueInput
}

/**
 * VehicleInfo deleteMany
 */
export type VehicleInfoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VehicleInfos to delete
   */
  where?: Prisma.VehicleInfoWhereInput
  /**
   * Limit how many VehicleInfos to delete.
   */
  limit?: number
}

/**
 * VehicleInfo.locations
 */
export type VehicleInfo$locationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocationLog
   */
  select?: Prisma.LocationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LocationLog
   */
  omit?: Prisma.LocationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocationLogInclude<ExtArgs> | null
  where?: Prisma.LocationLogWhereInput
  orderBy?: Prisma.LocationLogOrderByWithRelationInput | Prisma.LocationLogOrderByWithRelationInput[]
  cursor?: Prisma.LocationLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LocationLogScalarFieldEnum | Prisma.LocationLogScalarFieldEnum[]
}

/**
 * VehicleInfo.compliances
 */
export type VehicleInfo$compliancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null
  where?: Prisma.VehicleComplianceWhereInput
  orderBy?: Prisma.VehicleComplianceOrderByWithRelationInput | Prisma.VehicleComplianceOrderByWithRelationInput[]
  cursor?: Prisma.VehicleComplianceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VehicleComplianceScalarFieldEnum | Prisma.VehicleComplianceScalarFieldEnum[]
}

/**
 * VehicleInfo.geofech
 */
export type VehicleInfo$geofechArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Geofence
   */
  select?: Prisma.GeofenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Geofence
   */
  omit?: Prisma.GeofenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GeofenceInclude<ExtArgs> | null
  where?: Prisma.GeofenceWhereInput
  orderBy?: Prisma.GeofenceOrderByWithRelationInput | Prisma.GeofenceOrderByWithRelationInput[]
  cursor?: Prisma.GeofenceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GeofenceScalarFieldEnum | Prisma.GeofenceScalarFieldEnum[]
}

/**
 * VehicleInfo without action
 */
export type VehicleInfoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VehicleInfo
   */
  select?: Prisma.VehicleInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VehicleInfo
   */
  omit?: Prisma.VehicleInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleInfoInclude<ExtArgs> | null
}
