/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `VehicleCompliance` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model VehicleCompliance
 *
 */
export type VehicleComplianceModel =
  runtime.Types.Result.DefaultSelection<Prisma.$VehicleCompliancePayload>;

export type AggregateVehicleCompliance = {
  _count: VehicleComplianceCountAggregateOutputType | null;
  _avg: VehicleComplianceAvgAggregateOutputType | null;
  _sum: VehicleComplianceSumAggregateOutputType | null;
  _min: VehicleComplianceMinAggregateOutputType | null;
  _max: VehicleComplianceMaxAggregateOutputType | null;
};

export type VehicleComplianceAvgAggregateOutputType = {
  fuelQuantity: runtime.Decimal | null;
  fuelRate: runtime.Decimal | null;
  totalCost: runtime.Decimal | null;
  filledLat: runtime.Decimal | null;
  filledLng: runtime.Decimal | null;
};

export type VehicleComplianceSumAggregateOutputType = {
  fuelQuantity: runtime.Decimal | null;
  fuelRate: runtime.Decimal | null;
  totalCost: runtime.Decimal | null;
  filledLat: runtime.Decimal | null;
  filledLng: runtime.Decimal | null;
};

export type VehicleComplianceMinAggregateOutputType = {
  id: string | null;
  vehicleId: string | null;
  fuelQuantity: runtime.Decimal | null;
  fuelRate: runtime.Decimal | null;
  totalCost: runtime.Decimal | null;
  filledLat: runtime.Decimal | null;
  filledLng: runtime.Decimal | null;
  filledAddress: string | null;
  filledBy: string | null;
  receiptUrl: string | null;
  filledAt: Date | null;
  createdAt: Date | null;
};

export type VehicleComplianceMaxAggregateOutputType = {
  id: string | null;
  vehicleId: string | null;
  fuelQuantity: runtime.Decimal | null;
  fuelRate: runtime.Decimal | null;
  totalCost: runtime.Decimal | null;
  filledLat: runtime.Decimal | null;
  filledLng: runtime.Decimal | null;
  filledAddress: string | null;
  filledBy: string | null;
  receiptUrl: string | null;
  filledAt: Date | null;
  createdAt: Date | null;
};

export type VehicleComplianceCountAggregateOutputType = {
  id: number;
  vehicleId: number;
  fuelQuantity: number;
  fuelRate: number;
  totalCost: number;
  filledLat: number;
  filledLng: number;
  filledAddress: number;
  filledBy: number;
  receiptUrl: number;
  filledAt: number;
  createdAt: number;
  _all: number;
};

export type VehicleComplianceAvgAggregateInputType = {
  fuelQuantity?: true;
  fuelRate?: true;
  totalCost?: true;
  filledLat?: true;
  filledLng?: true;
};

export type VehicleComplianceSumAggregateInputType = {
  fuelQuantity?: true;
  fuelRate?: true;
  totalCost?: true;
  filledLat?: true;
  filledLng?: true;
};

export type VehicleComplianceMinAggregateInputType = {
  id?: true;
  vehicleId?: true;
  fuelQuantity?: true;
  fuelRate?: true;
  totalCost?: true;
  filledLat?: true;
  filledLng?: true;
  filledAddress?: true;
  filledBy?: true;
  receiptUrl?: true;
  filledAt?: true;
  createdAt?: true;
};

export type VehicleComplianceMaxAggregateInputType = {
  id?: true;
  vehicleId?: true;
  fuelQuantity?: true;
  fuelRate?: true;
  totalCost?: true;
  filledLat?: true;
  filledLng?: true;
  filledAddress?: true;
  filledBy?: true;
  receiptUrl?: true;
  filledAt?: true;
  createdAt?: true;
};

export type VehicleComplianceCountAggregateInputType = {
  id?: true;
  vehicleId?: true;
  fuelQuantity?: true;
  fuelRate?: true;
  totalCost?: true;
  filledLat?: true;
  filledLng?: true;
  filledAddress?: true;
  filledBy?: true;
  receiptUrl?: true;
  filledAt?: true;
  createdAt?: true;
  _all?: true;
};

export type VehicleComplianceAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which VehicleCompliance to aggregate.
   */
  where?: Prisma.VehicleComplianceWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of VehicleCompliances to fetch.
   */
  orderBy?:
    | Prisma.VehicleComplianceOrderByWithRelationInput
    | Prisma.VehicleComplianceOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.VehicleComplianceWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` VehicleCompliances from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` VehicleCompliances.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned VehicleCompliances
   **/
  _count?: true | VehicleComplianceCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: VehicleComplianceAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: VehicleComplianceSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: VehicleComplianceMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: VehicleComplianceMaxAggregateInputType;
};

export type GetVehicleComplianceAggregateType<T extends VehicleComplianceAggregateArgs> = {
  [P in keyof T & keyof AggregateVehicleCompliance]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVehicleCompliance[P]>
    : Prisma.GetScalarType<T[P], AggregateVehicleCompliance[P]>;
};

export type VehicleComplianceGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.VehicleComplianceWhereInput;
  orderBy?:
    | Prisma.VehicleComplianceOrderByWithAggregationInput
    | Prisma.VehicleComplianceOrderByWithAggregationInput[];
  by: Prisma.VehicleComplianceScalarFieldEnum[] | Prisma.VehicleComplianceScalarFieldEnum;
  having?: Prisma.VehicleComplianceScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: VehicleComplianceCountAggregateInputType | true;
  _avg?: VehicleComplianceAvgAggregateInputType;
  _sum?: VehicleComplianceSumAggregateInputType;
  _min?: VehicleComplianceMinAggregateInputType;
  _max?: VehicleComplianceMaxAggregateInputType;
};

export type VehicleComplianceGroupByOutputType = {
  id: string;
  vehicleId: string;
  fuelQuantity: runtime.Decimal;
  fuelRate: runtime.Decimal;
  totalCost: runtime.Decimal;
  filledLat: runtime.Decimal | null;
  filledLng: runtime.Decimal | null;
  filledAddress: string | null;
  filledBy: string;
  receiptUrl: string | null;
  filledAt: Date;
  createdAt: Date;
  _count: VehicleComplianceCountAggregateOutputType | null;
  _avg: VehicleComplianceAvgAggregateOutputType | null;
  _sum: VehicleComplianceSumAggregateOutputType | null;
  _min: VehicleComplianceMinAggregateOutputType | null;
  _max: VehicleComplianceMaxAggregateOutputType | null;
};

type GetVehicleComplianceGroupByPayload<T extends VehicleComplianceGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<VehicleComplianceGroupByOutputType, T['by']> & {
        [P in keyof T & keyof VehicleComplianceGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VehicleComplianceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VehicleComplianceGroupByOutputType[P]>;
      }
    >
  >;

export type VehicleComplianceWhereInput = {
  AND?: Prisma.VehicleComplianceWhereInput | Prisma.VehicleComplianceWhereInput[];
  OR?: Prisma.VehicleComplianceWhereInput[];
  NOT?: Prisma.VehicleComplianceWhereInput | Prisma.VehicleComplianceWhereInput[];
  id?: Prisma.UuidFilter<'VehicleCompliance'> | string;
  vehicleId?: Prisma.StringFilter<'VehicleCompliance'> | string;
  fuelQuantity?:
    | Prisma.DecimalFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.DecimalNullableFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.DecimalNullableFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.StringNullableFilter<'VehicleCompliance'> | string | null;
  filledBy?: Prisma.StringFilter<'VehicleCompliance'> | string;
  receiptUrl?: Prisma.StringNullableFilter<'VehicleCompliance'> | string | null;
  filledAt?: Prisma.DateTimeFilter<'VehicleCompliance'> | Date | string;
  createdAt?: Prisma.DateTimeFilter<'VehicleCompliance'> | Date | string;
  vehicle?: Prisma.XOR<Prisma.VehicleInfoScalarRelationFilter, Prisma.VehicleInfoWhereInput>;
};

export type VehicleComplianceOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  vehicleId?: Prisma.SortOrder;
  fuelQuantity?: Prisma.SortOrder;
  fuelRate?: Prisma.SortOrder;
  totalCost?: Prisma.SortOrder;
  filledLat?: Prisma.SortOrderInput | Prisma.SortOrder;
  filledLng?: Prisma.SortOrderInput | Prisma.SortOrder;
  filledAddress?: Prisma.SortOrderInput | Prisma.SortOrder;
  filledBy?: Prisma.SortOrder;
  receiptUrl?: Prisma.SortOrderInput | Prisma.SortOrder;
  filledAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  vehicle?: Prisma.VehicleInfoOrderByWithRelationInput;
};

export type VehicleComplianceWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.VehicleComplianceWhereInput | Prisma.VehicleComplianceWhereInput[];
    OR?: Prisma.VehicleComplianceWhereInput[];
    NOT?: Prisma.VehicleComplianceWhereInput | Prisma.VehicleComplianceWhereInput[];
    vehicleId?: Prisma.StringFilter<'VehicleCompliance'> | string;
    fuelQuantity?:
      | Prisma.DecimalFilter<'VehicleCompliance'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string;
    fuelRate?:
      | Prisma.DecimalFilter<'VehicleCompliance'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string;
    totalCost?:
      | Prisma.DecimalFilter<'VehicleCompliance'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string;
    filledLat?:
      | Prisma.DecimalNullableFilter<'VehicleCompliance'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string
      | null;
    filledLng?:
      | Prisma.DecimalNullableFilter<'VehicleCompliance'>
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string
      | null;
    filledAddress?: Prisma.StringNullableFilter<'VehicleCompliance'> | string | null;
    filledBy?: Prisma.StringFilter<'VehicleCompliance'> | string;
    receiptUrl?: Prisma.StringNullableFilter<'VehicleCompliance'> | string | null;
    filledAt?: Prisma.DateTimeFilter<'VehicleCompliance'> | Date | string;
    createdAt?: Prisma.DateTimeFilter<'VehicleCompliance'> | Date | string;
    vehicle?: Prisma.XOR<Prisma.VehicleInfoScalarRelationFilter, Prisma.VehicleInfoWhereInput>;
  },
  'id'
>;

export type VehicleComplianceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  vehicleId?: Prisma.SortOrder;
  fuelQuantity?: Prisma.SortOrder;
  fuelRate?: Prisma.SortOrder;
  totalCost?: Prisma.SortOrder;
  filledLat?: Prisma.SortOrderInput | Prisma.SortOrder;
  filledLng?: Prisma.SortOrderInput | Prisma.SortOrder;
  filledAddress?: Prisma.SortOrderInput | Prisma.SortOrder;
  filledBy?: Prisma.SortOrder;
  receiptUrl?: Prisma.SortOrderInput | Prisma.SortOrder;
  filledAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  _count?: Prisma.VehicleComplianceCountOrderByAggregateInput;
  _avg?: Prisma.VehicleComplianceAvgOrderByAggregateInput;
  _max?: Prisma.VehicleComplianceMaxOrderByAggregateInput;
  _min?: Prisma.VehicleComplianceMinOrderByAggregateInput;
  _sum?: Prisma.VehicleComplianceSumOrderByAggregateInput;
};

export type VehicleComplianceScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.VehicleComplianceScalarWhereWithAggregatesInput
    | Prisma.VehicleComplianceScalarWhereWithAggregatesInput[];
  OR?: Prisma.VehicleComplianceScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.VehicleComplianceScalarWhereWithAggregatesInput
    | Prisma.VehicleComplianceScalarWhereWithAggregatesInput[];
  id?: Prisma.UuidWithAggregatesFilter<'VehicleCompliance'> | string;
  vehicleId?: Prisma.StringWithAggregatesFilter<'VehicleCompliance'> | string;
  fuelQuantity?:
    | Prisma.DecimalWithAggregatesFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalWithAggregatesFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalWithAggregatesFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.DecimalNullableWithAggregatesFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.DecimalNullableWithAggregatesFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.StringNullableWithAggregatesFilter<'VehicleCompliance'> | string | null;
  filledBy?: Prisma.StringWithAggregatesFilter<'VehicleCompliance'> | string;
  receiptUrl?: Prisma.StringNullableWithAggregatesFilter<'VehicleCompliance'> | string | null;
  filledAt?: Prisma.DateTimeWithAggregatesFilter<'VehicleCompliance'> | Date | string;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'VehicleCompliance'> | Date | string;
};

export type VehicleComplianceCreateInput = {
  id?: string;
  fuelQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string;
  fuelRate: runtime.Decimal | runtime.DecimalJsLike | number | string;
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string;
  filledLat?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledLng?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledAddress?: string | null;
  filledBy: string;
  receiptUrl?: string | null;
  filledAt: Date | string;
  createdAt?: Date | string;
  vehicle: Prisma.VehicleInfoCreateNestedOneWithoutCompliancesInput;
};

export type VehicleComplianceUncheckedCreateInput = {
  id?: string;
  vehicleId: string;
  fuelQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string;
  fuelRate: runtime.Decimal | runtime.DecimalJsLike | number | string;
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string;
  filledLat?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledLng?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledAddress?: string | null;
  filledBy: string;
  receiptUrl?: string | null;
  filledAt: Date | string;
  createdAt?: Date | string;
};

export type VehicleComplianceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  fuelQuantity?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledBy?: Prisma.StringFieldUpdateOperationsInput | string;
  receiptUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  vehicle?: Prisma.VehicleInfoUpdateOneRequiredWithoutCompliancesNestedInput;
};

export type VehicleComplianceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  vehicleId?: Prisma.StringFieldUpdateOperationsInput | string;
  fuelQuantity?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledBy?: Prisma.StringFieldUpdateOperationsInput | string;
  receiptUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VehicleComplianceCreateManyInput = {
  id?: string;
  vehicleId: string;
  fuelQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string;
  fuelRate: runtime.Decimal | runtime.DecimalJsLike | number | string;
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string;
  filledLat?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledLng?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledAddress?: string | null;
  filledBy: string;
  receiptUrl?: string | null;
  filledAt: Date | string;
  createdAt?: Date | string;
};

export type VehicleComplianceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  fuelQuantity?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledBy?: Prisma.StringFieldUpdateOperationsInput | string;
  receiptUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VehicleComplianceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  vehicleId?: Prisma.StringFieldUpdateOperationsInput | string;
  fuelQuantity?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledBy?: Prisma.StringFieldUpdateOperationsInput | string;
  receiptUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VehicleComplianceListRelationFilter = {
  every?: Prisma.VehicleComplianceWhereInput;
  some?: Prisma.VehicleComplianceWhereInput;
  none?: Prisma.VehicleComplianceWhereInput;
};

export type VehicleComplianceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type VehicleComplianceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  vehicleId?: Prisma.SortOrder;
  fuelQuantity?: Prisma.SortOrder;
  fuelRate?: Prisma.SortOrder;
  totalCost?: Prisma.SortOrder;
  filledLat?: Prisma.SortOrder;
  filledLng?: Prisma.SortOrder;
  filledAddress?: Prisma.SortOrder;
  filledBy?: Prisma.SortOrder;
  receiptUrl?: Prisma.SortOrder;
  filledAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type VehicleComplianceAvgOrderByAggregateInput = {
  fuelQuantity?: Prisma.SortOrder;
  fuelRate?: Prisma.SortOrder;
  totalCost?: Prisma.SortOrder;
  filledLat?: Prisma.SortOrder;
  filledLng?: Prisma.SortOrder;
};

export type VehicleComplianceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  vehicleId?: Prisma.SortOrder;
  fuelQuantity?: Prisma.SortOrder;
  fuelRate?: Prisma.SortOrder;
  totalCost?: Prisma.SortOrder;
  filledLat?: Prisma.SortOrder;
  filledLng?: Prisma.SortOrder;
  filledAddress?: Prisma.SortOrder;
  filledBy?: Prisma.SortOrder;
  receiptUrl?: Prisma.SortOrder;
  filledAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type VehicleComplianceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  vehicleId?: Prisma.SortOrder;
  fuelQuantity?: Prisma.SortOrder;
  fuelRate?: Prisma.SortOrder;
  totalCost?: Prisma.SortOrder;
  filledLat?: Prisma.SortOrder;
  filledLng?: Prisma.SortOrder;
  filledAddress?: Prisma.SortOrder;
  filledBy?: Prisma.SortOrder;
  receiptUrl?: Prisma.SortOrder;
  filledAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type VehicleComplianceSumOrderByAggregateInput = {
  fuelQuantity?: Prisma.SortOrder;
  fuelRate?: Prisma.SortOrder;
  totalCost?: Prisma.SortOrder;
  filledLat?: Prisma.SortOrder;
  filledLng?: Prisma.SortOrder;
};

export type VehicleComplianceCreateNestedManyWithoutVehicleInput = {
  create?:
    | Prisma.XOR<
        Prisma.VehicleComplianceCreateWithoutVehicleInput,
        Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput
      >
    | Prisma.VehicleComplianceCreateWithoutVehicleInput[]
    | Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput[];
  connectOrCreate?:
    | Prisma.VehicleComplianceCreateOrConnectWithoutVehicleInput
    | Prisma.VehicleComplianceCreateOrConnectWithoutVehicleInput[];
  createMany?: Prisma.VehicleComplianceCreateManyVehicleInputEnvelope;
  connect?: Prisma.VehicleComplianceWhereUniqueInput | Prisma.VehicleComplianceWhereUniqueInput[];
};

export type VehicleComplianceUncheckedCreateNestedManyWithoutVehicleInput = {
  create?:
    | Prisma.XOR<
        Prisma.VehicleComplianceCreateWithoutVehicleInput,
        Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput
      >
    | Prisma.VehicleComplianceCreateWithoutVehicleInput[]
    | Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput[];
  connectOrCreate?:
    | Prisma.VehicleComplianceCreateOrConnectWithoutVehicleInput
    | Prisma.VehicleComplianceCreateOrConnectWithoutVehicleInput[];
  createMany?: Prisma.VehicleComplianceCreateManyVehicleInputEnvelope;
  connect?: Prisma.VehicleComplianceWhereUniqueInput | Prisma.VehicleComplianceWhereUniqueInput[];
};

export type VehicleComplianceUpdateManyWithoutVehicleNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VehicleComplianceCreateWithoutVehicleInput,
        Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput
      >
    | Prisma.VehicleComplianceCreateWithoutVehicleInput[]
    | Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput[];
  connectOrCreate?:
    | Prisma.VehicleComplianceCreateOrConnectWithoutVehicleInput
    | Prisma.VehicleComplianceCreateOrConnectWithoutVehicleInput[];
  upsert?:
    | Prisma.VehicleComplianceUpsertWithWhereUniqueWithoutVehicleInput
    | Prisma.VehicleComplianceUpsertWithWhereUniqueWithoutVehicleInput[];
  createMany?: Prisma.VehicleComplianceCreateManyVehicleInputEnvelope;
  set?: Prisma.VehicleComplianceWhereUniqueInput | Prisma.VehicleComplianceWhereUniqueInput[];
  disconnect?:
    | Prisma.VehicleComplianceWhereUniqueInput
    | Prisma.VehicleComplianceWhereUniqueInput[];
  delete?: Prisma.VehicleComplianceWhereUniqueInput | Prisma.VehicleComplianceWhereUniqueInput[];
  connect?: Prisma.VehicleComplianceWhereUniqueInput | Prisma.VehicleComplianceWhereUniqueInput[];
  update?:
    | Prisma.VehicleComplianceUpdateWithWhereUniqueWithoutVehicleInput
    | Prisma.VehicleComplianceUpdateWithWhereUniqueWithoutVehicleInput[];
  updateMany?:
    | Prisma.VehicleComplianceUpdateManyWithWhereWithoutVehicleInput
    | Prisma.VehicleComplianceUpdateManyWithWhereWithoutVehicleInput[];
  deleteMany?:
    | Prisma.VehicleComplianceScalarWhereInput
    | Prisma.VehicleComplianceScalarWhereInput[];
};

export type VehicleComplianceUncheckedUpdateManyWithoutVehicleNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VehicleComplianceCreateWithoutVehicleInput,
        Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput
      >
    | Prisma.VehicleComplianceCreateWithoutVehicleInput[]
    | Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput[];
  connectOrCreate?:
    | Prisma.VehicleComplianceCreateOrConnectWithoutVehicleInput
    | Prisma.VehicleComplianceCreateOrConnectWithoutVehicleInput[];
  upsert?:
    | Prisma.VehicleComplianceUpsertWithWhereUniqueWithoutVehicleInput
    | Prisma.VehicleComplianceUpsertWithWhereUniqueWithoutVehicleInput[];
  createMany?: Prisma.VehicleComplianceCreateManyVehicleInputEnvelope;
  set?: Prisma.VehicleComplianceWhereUniqueInput | Prisma.VehicleComplianceWhereUniqueInput[];
  disconnect?:
    | Prisma.VehicleComplianceWhereUniqueInput
    | Prisma.VehicleComplianceWhereUniqueInput[];
  delete?: Prisma.VehicleComplianceWhereUniqueInput | Prisma.VehicleComplianceWhereUniqueInput[];
  connect?: Prisma.VehicleComplianceWhereUniqueInput | Prisma.VehicleComplianceWhereUniqueInput[];
  update?:
    | Prisma.VehicleComplianceUpdateWithWhereUniqueWithoutVehicleInput
    | Prisma.VehicleComplianceUpdateWithWhereUniqueWithoutVehicleInput[];
  updateMany?:
    | Prisma.VehicleComplianceUpdateManyWithWhereWithoutVehicleInput
    | Prisma.VehicleComplianceUpdateManyWithWhereWithoutVehicleInput[];
  deleteMany?:
    | Prisma.VehicleComplianceScalarWhereInput
    | Prisma.VehicleComplianceScalarWhereInput[];
};

export type VehicleComplianceCreateWithoutVehicleInput = {
  id?: string;
  fuelQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string;
  fuelRate: runtime.Decimal | runtime.DecimalJsLike | number | string;
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string;
  filledLat?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledLng?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledAddress?: string | null;
  filledBy: string;
  receiptUrl?: string | null;
  filledAt: Date | string;
  createdAt?: Date | string;
};

export type VehicleComplianceUncheckedCreateWithoutVehicleInput = {
  id?: string;
  fuelQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string;
  fuelRate: runtime.Decimal | runtime.DecimalJsLike | number | string;
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string;
  filledLat?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledLng?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledAddress?: string | null;
  filledBy: string;
  receiptUrl?: string | null;
  filledAt: Date | string;
  createdAt?: Date | string;
};

export type VehicleComplianceCreateOrConnectWithoutVehicleInput = {
  where: Prisma.VehicleComplianceWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.VehicleComplianceCreateWithoutVehicleInput,
    Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput
  >;
};

export type VehicleComplianceCreateManyVehicleInputEnvelope = {
  data:
    | Prisma.VehicleComplianceCreateManyVehicleInput
    | Prisma.VehicleComplianceCreateManyVehicleInput[];
  skipDuplicates?: boolean;
};

export type VehicleComplianceUpsertWithWhereUniqueWithoutVehicleInput = {
  where: Prisma.VehicleComplianceWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.VehicleComplianceUpdateWithoutVehicleInput,
    Prisma.VehicleComplianceUncheckedUpdateWithoutVehicleInput
  >;
  create: Prisma.XOR<
    Prisma.VehicleComplianceCreateWithoutVehicleInput,
    Prisma.VehicleComplianceUncheckedCreateWithoutVehicleInput
  >;
};

export type VehicleComplianceUpdateWithWhereUniqueWithoutVehicleInput = {
  where: Prisma.VehicleComplianceWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.VehicleComplianceUpdateWithoutVehicleInput,
    Prisma.VehicleComplianceUncheckedUpdateWithoutVehicleInput
  >;
};

export type VehicleComplianceUpdateManyWithWhereWithoutVehicleInput = {
  where: Prisma.VehicleComplianceScalarWhereInput;
  data: Prisma.XOR<
    Prisma.VehicleComplianceUpdateManyMutationInput,
    Prisma.VehicleComplianceUncheckedUpdateManyWithoutVehicleInput
  >;
};

export type VehicleComplianceScalarWhereInput = {
  AND?: Prisma.VehicleComplianceScalarWhereInput | Prisma.VehicleComplianceScalarWhereInput[];
  OR?: Prisma.VehicleComplianceScalarWhereInput[];
  NOT?: Prisma.VehicleComplianceScalarWhereInput | Prisma.VehicleComplianceScalarWhereInput[];
  id?: Prisma.UuidFilter<'VehicleCompliance'> | string;
  vehicleId?: Prisma.StringFilter<'VehicleCompliance'> | string;
  fuelQuantity?:
    | Prisma.DecimalFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.DecimalNullableFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.DecimalNullableFilter<'VehicleCompliance'>
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.StringNullableFilter<'VehicleCompliance'> | string | null;
  filledBy?: Prisma.StringFilter<'VehicleCompliance'> | string;
  receiptUrl?: Prisma.StringNullableFilter<'VehicleCompliance'> | string | null;
  filledAt?: Prisma.DateTimeFilter<'VehicleCompliance'> | Date | string;
  createdAt?: Prisma.DateTimeFilter<'VehicleCompliance'> | Date | string;
};

export type VehicleComplianceCreateManyVehicleInput = {
  id?: string;
  fuelQuantity: runtime.Decimal | runtime.DecimalJsLike | number | string;
  fuelRate: runtime.Decimal | runtime.DecimalJsLike | number | string;
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string;
  filledLat?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledLng?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  filledAddress?: string | null;
  filledBy: string;
  receiptUrl?: string | null;
  filledAt: Date | string;
  createdAt?: Date | string;
};

export type VehicleComplianceUpdateWithoutVehicleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  fuelQuantity?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledBy?: Prisma.StringFieldUpdateOperationsInput | string;
  receiptUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VehicleComplianceUncheckedUpdateWithoutVehicleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  fuelQuantity?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledBy?: Prisma.StringFieldUpdateOperationsInput | string;
  receiptUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VehicleComplianceUncheckedUpdateManyWithoutVehicleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  fuelQuantity?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  fuelRate?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  totalCost?:
    | Prisma.DecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string;
  filledLat?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledLng?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  filledAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledBy?: Prisma.StringFieldUpdateOperationsInput | string;
  receiptUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  filledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type VehicleComplianceSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    vehicleId?: boolean;
    fuelQuantity?: boolean;
    fuelRate?: boolean;
    totalCost?: boolean;
    filledLat?: boolean;
    filledLng?: boolean;
    filledAddress?: boolean;
    filledBy?: boolean;
    receiptUrl?: boolean;
    filledAt?: boolean;
    createdAt?: boolean;
    vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['vehicleCompliance']
>;

export type VehicleComplianceSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    vehicleId?: boolean;
    fuelQuantity?: boolean;
    fuelRate?: boolean;
    totalCost?: boolean;
    filledLat?: boolean;
    filledLng?: boolean;
    filledAddress?: boolean;
    filledBy?: boolean;
    receiptUrl?: boolean;
    filledAt?: boolean;
    createdAt?: boolean;
    vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['vehicleCompliance']
>;

export type VehicleComplianceSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    vehicleId?: boolean;
    fuelQuantity?: boolean;
    fuelRate?: boolean;
    totalCost?: boolean;
    filledLat?: boolean;
    filledLng?: boolean;
    filledAddress?: boolean;
    filledBy?: boolean;
    receiptUrl?: boolean;
    filledAt?: boolean;
    createdAt?: boolean;
    vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['vehicleCompliance']
>;

export type VehicleComplianceSelectScalar = {
  id?: boolean;
  vehicleId?: boolean;
  fuelQuantity?: boolean;
  fuelRate?: boolean;
  totalCost?: boolean;
  filledLat?: boolean;
  filledLng?: boolean;
  filledAddress?: boolean;
  filledBy?: boolean;
  receiptUrl?: boolean;
  filledAt?: boolean;
  createdAt?: boolean;
};

export type VehicleComplianceOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'vehicleId'
  | 'fuelQuantity'
  | 'fuelRate'
  | 'totalCost'
  | 'filledLat'
  | 'filledLng'
  | 'filledAddress'
  | 'filledBy'
  | 'receiptUrl'
  | 'filledAt'
  | 'createdAt',
  ExtArgs['result']['vehicleCompliance']
>;
export type VehicleComplianceInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
};
export type VehicleComplianceIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
};
export type VehicleComplianceIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  vehicle?: boolean | Prisma.VehicleInfoDefaultArgs<ExtArgs>;
};

export type $VehicleCompliancePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'VehicleCompliance';
  objects: {
    vehicle: Prisma.$VehicleInfoPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      vehicleId: string;
      fuelQuantity: runtime.Decimal;
      fuelRate: runtime.Decimal;
      totalCost: runtime.Decimal;
      filledLat: runtime.Decimal | null;
      filledLng: runtime.Decimal | null;
      filledAddress: string | null;
      filledBy: string;
      receiptUrl: string | null;
      filledAt: Date;
      createdAt: Date;
    },
    ExtArgs['result']['vehicleCompliance']
  >;
  composites: {};
};

export type VehicleComplianceGetPayload<
  S extends boolean | null | undefined | VehicleComplianceDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$VehicleCompliancePayload, S>;

export type VehicleComplianceCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<VehicleComplianceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: VehicleComplianceCountAggregateInputType | true;
};

export interface VehicleComplianceDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['VehicleCompliance'];
    meta: { name: 'VehicleCompliance' };
  };
  /**
   * Find zero or one VehicleCompliance that matches the filter.
   * @param {VehicleComplianceFindUniqueArgs} args - Arguments to find a VehicleCompliance
   * @example
   * // Get one VehicleCompliance
   * const vehicleCompliance = await prisma.vehicleCompliance.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VehicleComplianceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, VehicleComplianceFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleComplianceClient<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one VehicleCompliance that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VehicleComplianceFindUniqueOrThrowArgs} args - Arguments to find a VehicleCompliance
   * @example
   * // Get one VehicleCompliance
   * const vehicleCompliance = await prisma.vehicleCompliance.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VehicleComplianceFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, VehicleComplianceFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleComplianceClient<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first VehicleCompliance that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleComplianceFindFirstArgs} args - Arguments to find a VehicleCompliance
   * @example
   * // Get one VehicleCompliance
   * const vehicleCompliance = await prisma.vehicleCompliance.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VehicleComplianceFindFirstArgs>(
    args?: Prisma.SelectSubset<T, VehicleComplianceFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleComplianceClient<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first VehicleCompliance that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleComplianceFindFirstOrThrowArgs} args - Arguments to find a VehicleCompliance
   * @example
   * // Get one VehicleCompliance
   * const vehicleCompliance = await prisma.vehicleCompliance.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VehicleComplianceFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, VehicleComplianceFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleComplianceClient<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more VehicleCompliances that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleComplianceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VehicleCompliances
   * const vehicleCompliances = await prisma.vehicleCompliance.findMany()
   *
   * // Get first 10 VehicleCompliances
   * const vehicleCompliances = await prisma.vehicleCompliance.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const vehicleComplianceWithIdOnly = await prisma.vehicleCompliance.findMany({ select: { id: true } })
   *
   */
  findMany<T extends VehicleComplianceFindManyArgs>(
    args?: Prisma.SelectSubset<T, VehicleComplianceFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a VehicleCompliance.
   * @param {VehicleComplianceCreateArgs} args - Arguments to create a VehicleCompliance.
   * @example
   * // Create one VehicleCompliance
   * const VehicleCompliance = await prisma.vehicleCompliance.create({
   *   data: {
   *     // ... data to create a VehicleCompliance
   *   }
   * })
   *
   */
  create<T extends VehicleComplianceCreateArgs>(
    args: Prisma.SelectSubset<T, VehicleComplianceCreateArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleComplianceClient<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many VehicleCompliances.
   * @param {VehicleComplianceCreateManyArgs} args - Arguments to create many VehicleCompliances.
   * @example
   * // Create many VehicleCompliances
   * const vehicleCompliance = await prisma.vehicleCompliance.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends VehicleComplianceCreateManyArgs>(
    args?: Prisma.SelectSubset<T, VehicleComplianceCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many VehicleCompliances and returns the data saved in the database.
   * @param {VehicleComplianceCreateManyAndReturnArgs} args - Arguments to create many VehicleCompliances.
   * @example
   * // Create many VehicleCompliances
   * const vehicleCompliance = await prisma.vehicleCompliance.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many VehicleCompliances and only return the `id`
   * const vehicleComplianceWithIdOnly = await prisma.vehicleCompliance.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends VehicleComplianceCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, VehicleComplianceCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a VehicleCompliance.
   * @param {VehicleComplianceDeleteArgs} args - Arguments to delete one VehicleCompliance.
   * @example
   * // Delete one VehicleCompliance
   * const VehicleCompliance = await prisma.vehicleCompliance.delete({
   *   where: {
   *     // ... filter to delete one VehicleCompliance
   *   }
   * })
   *
   */
  delete<T extends VehicleComplianceDeleteArgs>(
    args: Prisma.SelectSubset<T, VehicleComplianceDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleComplianceClient<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one VehicleCompliance.
   * @param {VehicleComplianceUpdateArgs} args - Arguments to update one VehicleCompliance.
   * @example
   * // Update one VehicleCompliance
   * const vehicleCompliance = await prisma.vehicleCompliance.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends VehicleComplianceUpdateArgs>(
    args: Prisma.SelectSubset<T, VehicleComplianceUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleComplianceClient<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more VehicleCompliances.
   * @param {VehicleComplianceDeleteManyArgs} args - Arguments to filter VehicleCompliances to delete.
   * @example
   * // Delete a few VehicleCompliances
   * const { count } = await prisma.vehicleCompliance.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends VehicleComplianceDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, VehicleComplianceDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more VehicleCompliances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleComplianceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VehicleCompliances
   * const vehicleCompliance = await prisma.vehicleCompliance.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends VehicleComplianceUpdateManyArgs>(
    args: Prisma.SelectSubset<T, VehicleComplianceUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more VehicleCompliances and returns the data updated in the database.
   * @param {VehicleComplianceUpdateManyAndReturnArgs} args - Arguments to update many VehicleCompliances.
   * @example
   * // Update many VehicleCompliances
   * const vehicleCompliance = await prisma.vehicleCompliance.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more VehicleCompliances and only return the `id`
   * const vehicleComplianceWithIdOnly = await prisma.vehicleCompliance.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends VehicleComplianceUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, VehicleComplianceUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one VehicleCompliance.
   * @param {VehicleComplianceUpsertArgs} args - Arguments to update or create a VehicleCompliance.
   * @example
   * // Update or create a VehicleCompliance
   * const vehicleCompliance = await prisma.vehicleCompliance.upsert({
   *   create: {
   *     // ... data to create a VehicleCompliance
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VehicleCompliance we want to update
   *   }
   * })
   */
  upsert<T extends VehicleComplianceUpsertArgs>(
    args: Prisma.SelectSubset<T, VehicleComplianceUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleComplianceClient<
    runtime.Types.Result.GetResult<
      Prisma.$VehicleCompliancePayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of VehicleCompliances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleComplianceCountArgs} args - Arguments to filter VehicleCompliances to count.
   * @example
   * // Count the number of VehicleCompliances
   * const count = await prisma.vehicleCompliance.count({
   *   where: {
   *     // ... the filter for the VehicleCompliances we want to count
   *   }
   * })
   **/
  count<T extends VehicleComplianceCountArgs>(
    args?: Prisma.Subset<T, VehicleComplianceCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VehicleComplianceCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a VehicleCompliance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleComplianceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends VehicleComplianceAggregateArgs>(
    args: Prisma.Subset<T, VehicleComplianceAggregateArgs>
  ): Prisma.PrismaPromise<GetVehicleComplianceAggregateType<T>>;

  /**
   * Group by VehicleCompliance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VehicleComplianceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends VehicleComplianceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VehicleComplianceGroupByArgs['orderBy'] }
      : { orderBy?: VehicleComplianceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, VehicleComplianceGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors
    ? GetVehicleComplianceGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the VehicleCompliance model
   */
  readonly fields: VehicleComplianceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VehicleCompliance.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VehicleComplianceClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  vehicle<T extends Prisma.VehicleInfoDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.VehicleInfoDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__VehicleInfoClient<
    | runtime.Types.Result.GetResult<
        Prisma.$VehicleInfoPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the VehicleCompliance model
 */
export interface VehicleComplianceFieldRefs {
  readonly id: Prisma.FieldRef<'VehicleCompliance', 'String'>;
  readonly vehicleId: Prisma.FieldRef<'VehicleCompliance', 'String'>;
  readonly fuelQuantity: Prisma.FieldRef<'VehicleCompliance', 'Decimal'>;
  readonly fuelRate: Prisma.FieldRef<'VehicleCompliance', 'Decimal'>;
  readonly totalCost: Prisma.FieldRef<'VehicleCompliance', 'Decimal'>;
  readonly filledLat: Prisma.FieldRef<'VehicleCompliance', 'Decimal'>;
  readonly filledLng: Prisma.FieldRef<'VehicleCompliance', 'Decimal'>;
  readonly filledAddress: Prisma.FieldRef<'VehicleCompliance', 'String'>;
  readonly filledBy: Prisma.FieldRef<'VehicleCompliance', 'String'>;
  readonly receiptUrl: Prisma.FieldRef<'VehicleCompliance', 'String'>;
  readonly filledAt: Prisma.FieldRef<'VehicleCompliance', 'DateTime'>;
  readonly createdAt: Prisma.FieldRef<'VehicleCompliance', 'DateTime'>;
}

// Custom InputTypes
/**
 * VehicleCompliance findUnique
 */
export type VehicleComplianceFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * Filter, which VehicleCompliance to fetch.
   */
  where: Prisma.VehicleComplianceWhereUniqueInput;
};

/**
 * VehicleCompliance findUniqueOrThrow
 */
export type VehicleComplianceFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * Filter, which VehicleCompliance to fetch.
   */
  where: Prisma.VehicleComplianceWhereUniqueInput;
};

/**
 * VehicleCompliance findFirst
 */
export type VehicleComplianceFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * Filter, which VehicleCompliance to fetch.
   */
  where?: Prisma.VehicleComplianceWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of VehicleCompliances to fetch.
   */
  orderBy?:
    | Prisma.VehicleComplianceOrderByWithRelationInput
    | Prisma.VehicleComplianceOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for VehicleCompliances.
   */
  cursor?: Prisma.VehicleComplianceWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` VehicleCompliances from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` VehicleCompliances.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of VehicleCompliances.
   */
  distinct?: Prisma.VehicleComplianceScalarFieldEnum | Prisma.VehicleComplianceScalarFieldEnum[];
};

/**
 * VehicleCompliance findFirstOrThrow
 */
export type VehicleComplianceFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * Filter, which VehicleCompliance to fetch.
   */
  where?: Prisma.VehicleComplianceWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of VehicleCompliances to fetch.
   */
  orderBy?:
    | Prisma.VehicleComplianceOrderByWithRelationInput
    | Prisma.VehicleComplianceOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for VehicleCompliances.
   */
  cursor?: Prisma.VehicleComplianceWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` VehicleCompliances from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` VehicleCompliances.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of VehicleCompliances.
   */
  distinct?: Prisma.VehicleComplianceScalarFieldEnum | Prisma.VehicleComplianceScalarFieldEnum[];
};

/**
 * VehicleCompliance findMany
 */
export type VehicleComplianceFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * Filter, which VehicleCompliances to fetch.
   */
  where?: Prisma.VehicleComplianceWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of VehicleCompliances to fetch.
   */
  orderBy?:
    | Prisma.VehicleComplianceOrderByWithRelationInput
    | Prisma.VehicleComplianceOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing VehicleCompliances.
   */
  cursor?: Prisma.VehicleComplianceWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` VehicleCompliances from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` VehicleCompliances.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of VehicleCompliances.
   */
  distinct?: Prisma.VehicleComplianceScalarFieldEnum | Prisma.VehicleComplianceScalarFieldEnum[];
};

/**
 * VehicleCompliance create
 */
export type VehicleComplianceCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * The data needed to create a VehicleCompliance.
   */
  data: Prisma.XOR<
    Prisma.VehicleComplianceCreateInput,
    Prisma.VehicleComplianceUncheckedCreateInput
  >;
};

/**
 * VehicleCompliance createMany
 */
export type VehicleComplianceCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many VehicleCompliances.
   */
  data: Prisma.VehicleComplianceCreateManyInput | Prisma.VehicleComplianceCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * VehicleCompliance createManyAndReturn
 */
export type VehicleComplianceCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * The data used to create many VehicleCompliances.
   */
  data: Prisma.VehicleComplianceCreateManyInput | Prisma.VehicleComplianceCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * VehicleCompliance update
 */
export type VehicleComplianceUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * The data needed to update a VehicleCompliance.
   */
  data: Prisma.XOR<
    Prisma.VehicleComplianceUpdateInput,
    Prisma.VehicleComplianceUncheckedUpdateInput
  >;
  /**
   * Choose, which VehicleCompliance to update.
   */
  where: Prisma.VehicleComplianceWhereUniqueInput;
};

/**
 * VehicleCompliance updateMany
 */
export type VehicleComplianceUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update VehicleCompliances.
   */
  data: Prisma.XOR<
    Prisma.VehicleComplianceUpdateManyMutationInput,
    Prisma.VehicleComplianceUncheckedUpdateManyInput
  >;
  /**
   * Filter which VehicleCompliances to update
   */
  where?: Prisma.VehicleComplianceWhereInput;
  /**
   * Limit how many VehicleCompliances to update.
   */
  limit?: number;
};

/**
 * VehicleCompliance updateManyAndReturn
 */
export type VehicleComplianceUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * The data used to update VehicleCompliances.
   */
  data: Prisma.XOR<
    Prisma.VehicleComplianceUpdateManyMutationInput,
    Prisma.VehicleComplianceUncheckedUpdateManyInput
  >;
  /**
   * Filter which VehicleCompliances to update
   */
  where?: Prisma.VehicleComplianceWhereInput;
  /**
   * Limit how many VehicleCompliances to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * VehicleCompliance upsert
 */
export type VehicleComplianceUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * The filter to search for the VehicleCompliance to update in case it exists.
   */
  where: Prisma.VehicleComplianceWhereUniqueInput;
  /**
   * In case the VehicleCompliance found by the `where` argument doesn't exist, create a new VehicleCompliance with this data.
   */
  create: Prisma.XOR<
    Prisma.VehicleComplianceCreateInput,
    Prisma.VehicleComplianceUncheckedCreateInput
  >;
  /**
   * In case the VehicleCompliance was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.VehicleComplianceUpdateInput,
    Prisma.VehicleComplianceUncheckedUpdateInput
  >;
};

/**
 * VehicleCompliance delete
 */
export type VehicleComplianceDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
  /**
   * Filter which VehicleCompliance to delete.
   */
  where: Prisma.VehicleComplianceWhereUniqueInput;
};

/**
 * VehicleCompliance deleteMany
 */
export type VehicleComplianceDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which VehicleCompliances to delete
   */
  where?: Prisma.VehicleComplianceWhereInput;
  /**
   * Limit how many VehicleCompliances to delete.
   */
  limit?: number;
};

/**
 * VehicleCompliance without action
 */
export type VehicleComplianceDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VehicleCompliance
   */
  select?: Prisma.VehicleComplianceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the VehicleCompliance
   */
  omit?: Prisma.VehicleComplianceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VehicleComplianceInclude<ExtArgs> | null;
};
